/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomerFiscalEntitiesResponseAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerFiscalEntitiesResponseAddress{}

// CustomerFiscalEntitiesResponseAddress struct for CustomerFiscalEntitiesResponseAddress
type CustomerFiscalEntitiesResponseAddress struct {
	Object string `json:"object"`
	PostalCode string `json:"postal_code"`
	Street1 NullableString `json:"street1,omitempty"`
	ExternalNumber NullableString `json:"external_number,omitempty"`
	City NullableString `json:"city,omitempty"`
	Country NullableString `json:"country,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerFiscalEntitiesResponseAddress CustomerFiscalEntitiesResponseAddress

// NewCustomerFiscalEntitiesResponseAddress instantiates a new CustomerFiscalEntitiesResponseAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerFiscalEntitiesResponseAddress(object string, postalCode string) *CustomerFiscalEntitiesResponseAddress {
	this := CustomerFiscalEntitiesResponseAddress{}
	this.Object = object
	this.PostalCode = postalCode
	return &this
}

// NewCustomerFiscalEntitiesResponseAddressWithDefaults instantiates a new CustomerFiscalEntitiesResponseAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerFiscalEntitiesResponseAddressWithDefaults() *CustomerFiscalEntitiesResponseAddress {
	this := CustomerFiscalEntitiesResponseAddress{}
	return &this
}

// GetObject returns the Object field value
func (o *CustomerFiscalEntitiesResponseAddress) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *CustomerFiscalEntitiesResponseAddress) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *CustomerFiscalEntitiesResponseAddress) SetObject(v string) {
	o.Object = v
}

// GetPostalCode returns the PostalCode field value
func (o *CustomerFiscalEntitiesResponseAddress) GetPostalCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value
// and a boolean to check if the value has been set.
func (o *CustomerFiscalEntitiesResponseAddress) GetPostalCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PostalCode, true
}

// SetPostalCode sets field value
func (o *CustomerFiscalEntitiesResponseAddress) SetPostalCode(v string) {
	o.PostalCode = v
}

// GetStreet1 returns the Street1 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerFiscalEntitiesResponseAddress) GetStreet1() string {
	if o == nil || IsNil(o.Street1.Get()) {
		var ret string
		return ret
	}
	return *o.Street1.Get()
}

// GetStreet1Ok returns a tuple with the Street1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerFiscalEntitiesResponseAddress) GetStreet1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Street1.Get(), o.Street1.IsSet()
}

// HasStreet1 returns a boolean if a field has been set.
func (o *CustomerFiscalEntitiesResponseAddress) HasStreet1() bool {
	if o != nil && o.Street1.IsSet() {
		return true
	}

	return false
}

// SetStreet1 gets a reference to the given NullableString and assigns it to the Street1 field.
func (o *CustomerFiscalEntitiesResponseAddress) SetStreet1(v string) {
	o.Street1.Set(&v)
}
// SetStreet1Nil sets the value for Street1 to be an explicit nil
func (o *CustomerFiscalEntitiesResponseAddress) SetStreet1Nil() {
	o.Street1.Set(nil)
}

// UnsetStreet1 ensures that no value is present for Street1, not even an explicit nil
func (o *CustomerFiscalEntitiesResponseAddress) UnsetStreet1() {
	o.Street1.Unset()
}

// GetExternalNumber returns the ExternalNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerFiscalEntitiesResponseAddress) GetExternalNumber() string {
	if o == nil || IsNil(o.ExternalNumber.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalNumber.Get()
}

// GetExternalNumberOk returns a tuple with the ExternalNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerFiscalEntitiesResponseAddress) GetExternalNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalNumber.Get(), o.ExternalNumber.IsSet()
}

// HasExternalNumber returns a boolean if a field has been set.
func (o *CustomerFiscalEntitiesResponseAddress) HasExternalNumber() bool {
	if o != nil && o.ExternalNumber.IsSet() {
		return true
	}

	return false
}

// SetExternalNumber gets a reference to the given NullableString and assigns it to the ExternalNumber field.
func (o *CustomerFiscalEntitiesResponseAddress) SetExternalNumber(v string) {
	o.ExternalNumber.Set(&v)
}
// SetExternalNumberNil sets the value for ExternalNumber to be an explicit nil
func (o *CustomerFiscalEntitiesResponseAddress) SetExternalNumberNil() {
	o.ExternalNumber.Set(nil)
}

// UnsetExternalNumber ensures that no value is present for ExternalNumber, not even an explicit nil
func (o *CustomerFiscalEntitiesResponseAddress) UnsetExternalNumber() {
	o.ExternalNumber.Unset()
}

// GetCity returns the City field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerFiscalEntitiesResponseAddress) GetCity() string {
	if o == nil || IsNil(o.City.Get()) {
		var ret string
		return ret
	}
	return *o.City.Get()
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerFiscalEntitiesResponseAddress) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.City.Get(), o.City.IsSet()
}

// HasCity returns a boolean if a field has been set.
func (o *CustomerFiscalEntitiesResponseAddress) HasCity() bool {
	if o != nil && o.City.IsSet() {
		return true
	}

	return false
}

// SetCity gets a reference to the given NullableString and assigns it to the City field.
func (o *CustomerFiscalEntitiesResponseAddress) SetCity(v string) {
	o.City.Set(&v)
}
// SetCityNil sets the value for City to be an explicit nil
func (o *CustomerFiscalEntitiesResponseAddress) SetCityNil() {
	o.City.Set(nil)
}

// UnsetCity ensures that no value is present for City, not even an explicit nil
func (o *CustomerFiscalEntitiesResponseAddress) UnsetCity() {
	o.City.Unset()
}

// GetCountry returns the Country field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerFiscalEntitiesResponseAddress) GetCountry() string {
	if o == nil || IsNil(o.Country.Get()) {
		var ret string
		return ret
	}
	return *o.Country.Get()
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerFiscalEntitiesResponseAddress) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Country.Get(), o.Country.IsSet()
}

// HasCountry returns a boolean if a field has been set.
func (o *CustomerFiscalEntitiesResponseAddress) HasCountry() bool {
	if o != nil && o.Country.IsSet() {
		return true
	}

	return false
}

// SetCountry gets a reference to the given NullableString and assigns it to the Country field.
func (o *CustomerFiscalEntitiesResponseAddress) SetCountry(v string) {
	o.Country.Set(&v)
}
// SetCountryNil sets the value for Country to be an explicit nil
func (o *CustomerFiscalEntitiesResponseAddress) SetCountryNil() {
	o.Country.Set(nil)
}

// UnsetCountry ensures that no value is present for Country, not even an explicit nil
func (o *CustomerFiscalEntitiesResponseAddress) UnsetCountry() {
	o.Country.Unset()
}

func (o CustomerFiscalEntitiesResponseAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerFiscalEntitiesResponseAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["object"] = o.Object
	toSerialize["postal_code"] = o.PostalCode
	if o.Street1.IsSet() {
		toSerialize["street1"] = o.Street1.Get()
	}
	if o.ExternalNumber.IsSet() {
		toSerialize["external_number"] = o.ExternalNumber.Get()
	}
	if o.City.IsSet() {
		toSerialize["city"] = o.City.Get()
	}
	if o.Country.IsSet() {
		toSerialize["country"] = o.Country.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerFiscalEntitiesResponseAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object",
		"postal_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerFiscalEntitiesResponseAddress := _CustomerFiscalEntitiesResponseAddress{}

	err = json.Unmarshal(data, &varCustomerFiscalEntitiesResponseAddress)

	if err != nil {
		return err
	}

	*o = CustomerFiscalEntitiesResponseAddress(varCustomerFiscalEntitiesResponseAddress)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "object")
		delete(additionalProperties, "postal_code")
		delete(additionalProperties, "street1")
		delete(additionalProperties, "external_number")
		delete(additionalProperties, "city")
		delete(additionalProperties, "country")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerFiscalEntitiesResponseAddress struct {
	value *CustomerFiscalEntitiesResponseAddress
	isSet bool
}

func (v NullableCustomerFiscalEntitiesResponseAddress) Get() *CustomerFiscalEntitiesResponseAddress {
	return v.value
}

func (v *NullableCustomerFiscalEntitiesResponseAddress) Set(val *CustomerFiscalEntitiesResponseAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerFiscalEntitiesResponseAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerFiscalEntitiesResponseAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerFiscalEntitiesResponseAddress(val *CustomerFiscalEntitiesResponseAddress) *NullableCustomerFiscalEntitiesResponseAddress {
	return &NullableCustomerFiscalEntitiesResponseAddress{value: val, isSet: true}
}

func (v NullableCustomerFiscalEntitiesResponseAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerFiscalEntitiesResponseAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


