/*
Femsa API

Femsa sdk

API version: 2.1.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
)

// checks if the OrderResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderResponse{}

// OrderResponse Order model. Some nested resources are returned as list previews (for example: `charges`, `line_items`), and may be `null` depending on the request/context. The `checkout` field is only present when the order is linked to a checkout (`channel.checkout_request_id`). 
type OrderResponse struct {
	Id *string `json:"id,omitempty"`
	Object *string `json:"object,omitempty"`
	Livemode *bool `json:"livemode,omitempty"`
	Amount *int32 `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
	// Current payment status of the order. It can be `null` for orders without payment information yet.
	PaymentStatus NullableString `json:"payment_status,omitempty"`
	AmountRefunded *int32 `json:"amount_refunded,omitempty"`
	// Indicates whether the order uses split payments (when available/configured).
	SplitPayment NullableBool `json:"split_payment,omitempty"`
	// Metadata attached to the order.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Indicates whether the order is currently refundable.
	IsRefundable *bool `json:"is_refundable,omitempty"`
	CreatedAt *int64 `json:"created_at,omitempty"`
	UpdatedAt *int64 `json:"updated_at,omitempty"`
	CustomerInfo *OrderResponseCustomerInfo `json:"customer_info,omitempty"`
	ShippingContact NullableOrderResponseShippingContact `json:"shipping_contact,omitempty"`
	Channel NullableOrderResponseChannel `json:"channel,omitempty"`
	FiscalEntity NullableOrderFiscalEntityResponse `json:"fiscal_entity,omitempty"`
	Checkout *OrderResponseCheckout `json:"checkout,omitempty"`
	LineItems *OrderResponseProducts `json:"line_items,omitempty"`
	DiscountLines *OrderResponseDiscountLines `json:"discount_lines,omitempty"`
	Charges *OrderResponseCharges `json:"charges,omitempty"`
	// Partial reference information (when applicable). Structure may vary depending on the payment flow.
	PartialReference map[string]interface{} `json:"partial_reference,omitempty"`
	// Additional payment information (when available). Structure may vary.
	PaymentsInfo map[string]interface{} `json:"payments_info,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderResponse OrderResponse

// NewOrderResponse instantiates a new OrderResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderResponse() *OrderResponse {
	this := OrderResponse{}
	return &this
}

// NewOrderResponseWithDefaults instantiates a new OrderResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderResponseWithDefaults() *OrderResponse {
	this := OrderResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OrderResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OrderResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OrderResponse) SetId(v string) {
	o.Id = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *OrderResponse) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *OrderResponse) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *OrderResponse) SetObject(v string) {
	o.Object = &v
}

// GetLivemode returns the Livemode field value if set, zero value otherwise.
func (o *OrderResponse) GetLivemode() bool {
	if o == nil || IsNil(o.Livemode) {
		var ret bool
		return ret
	}
	return *o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetLivemodeOk() (*bool, bool) {
	if o == nil || IsNil(o.Livemode) {
		return nil, false
	}
	return o.Livemode, true
}

// HasLivemode returns a boolean if a field has been set.
func (o *OrderResponse) HasLivemode() bool {
	if o != nil && !IsNil(o.Livemode) {
		return true
	}

	return false
}

// SetLivemode gets a reference to the given bool and assigns it to the Livemode field.
func (o *OrderResponse) SetLivemode(v bool) {
	o.Livemode = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *OrderResponse) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *OrderResponse) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *OrderResponse) SetAmount(v int32) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *OrderResponse) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *OrderResponse) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *OrderResponse) SetCurrency(v string) {
	o.Currency = &v
}

// GetPaymentStatus returns the PaymentStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderResponse) GetPaymentStatus() string {
	if o == nil || IsNil(o.PaymentStatus.Get()) {
		var ret string
		return ret
	}
	return *o.PaymentStatus.Get()
}

// GetPaymentStatusOk returns a tuple with the PaymentStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderResponse) GetPaymentStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaymentStatus.Get(), o.PaymentStatus.IsSet()
}

// HasPaymentStatus returns a boolean if a field has been set.
func (o *OrderResponse) HasPaymentStatus() bool {
	if o != nil && o.PaymentStatus.IsSet() {
		return true
	}

	return false
}

// SetPaymentStatus gets a reference to the given NullableString and assigns it to the PaymentStatus field.
func (o *OrderResponse) SetPaymentStatus(v string) {
	o.PaymentStatus.Set(&v)
}
// SetPaymentStatusNil sets the value for PaymentStatus to be an explicit nil
func (o *OrderResponse) SetPaymentStatusNil() {
	o.PaymentStatus.Set(nil)
}

// UnsetPaymentStatus ensures that no value is present for PaymentStatus, not even an explicit nil
func (o *OrderResponse) UnsetPaymentStatus() {
	o.PaymentStatus.Unset()
}

// GetAmountRefunded returns the AmountRefunded field value if set, zero value otherwise.
func (o *OrderResponse) GetAmountRefunded() int32 {
	if o == nil || IsNil(o.AmountRefunded) {
		var ret int32
		return ret
	}
	return *o.AmountRefunded
}

// GetAmountRefundedOk returns a tuple with the AmountRefunded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetAmountRefundedOk() (*int32, bool) {
	if o == nil || IsNil(o.AmountRefunded) {
		return nil, false
	}
	return o.AmountRefunded, true
}

// HasAmountRefunded returns a boolean if a field has been set.
func (o *OrderResponse) HasAmountRefunded() bool {
	if o != nil && !IsNil(o.AmountRefunded) {
		return true
	}

	return false
}

// SetAmountRefunded gets a reference to the given int32 and assigns it to the AmountRefunded field.
func (o *OrderResponse) SetAmountRefunded(v int32) {
	o.AmountRefunded = &v
}

// GetSplitPayment returns the SplitPayment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderResponse) GetSplitPayment() bool {
	if o == nil || IsNil(o.SplitPayment.Get()) {
		var ret bool
		return ret
	}
	return *o.SplitPayment.Get()
}

// GetSplitPaymentOk returns a tuple with the SplitPayment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderResponse) GetSplitPaymentOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SplitPayment.Get(), o.SplitPayment.IsSet()
}

// HasSplitPayment returns a boolean if a field has been set.
func (o *OrderResponse) HasSplitPayment() bool {
	if o != nil && o.SplitPayment.IsSet() {
		return true
	}

	return false
}

// SetSplitPayment gets a reference to the given NullableBool and assigns it to the SplitPayment field.
func (o *OrderResponse) SetSplitPayment(v bool) {
	o.SplitPayment.Set(&v)
}
// SetSplitPaymentNil sets the value for SplitPayment to be an explicit nil
func (o *OrderResponse) SetSplitPaymentNil() {
	o.SplitPayment.Set(nil)
}

// UnsetSplitPayment ensures that no value is present for SplitPayment, not even an explicit nil
func (o *OrderResponse) UnsetSplitPayment() {
	o.SplitPayment.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *OrderResponse) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *OrderResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *OrderResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetIsRefundable returns the IsRefundable field value if set, zero value otherwise.
func (o *OrderResponse) GetIsRefundable() bool {
	if o == nil || IsNil(o.IsRefundable) {
		var ret bool
		return ret
	}
	return *o.IsRefundable
}

// GetIsRefundableOk returns a tuple with the IsRefundable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetIsRefundableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRefundable) {
		return nil, false
	}
	return o.IsRefundable, true
}

// HasIsRefundable returns a boolean if a field has been set.
func (o *OrderResponse) HasIsRefundable() bool {
	if o != nil && !IsNil(o.IsRefundable) {
		return true
	}

	return false
}

// SetIsRefundable gets a reference to the given bool and assigns it to the IsRefundable field.
func (o *OrderResponse) SetIsRefundable(v bool) {
	o.IsRefundable = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *OrderResponse) GetCreatedAt() int64 {
	if o == nil || IsNil(o.CreatedAt) {
		var ret int64
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetCreatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *OrderResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given int64 and assigns it to the CreatedAt field.
func (o *OrderResponse) SetCreatedAt(v int64) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *OrderResponse) GetUpdatedAt() int64 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int64
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetUpdatedAtOk() (*int64, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *OrderResponse) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int64 and assigns it to the UpdatedAt field.
func (o *OrderResponse) SetUpdatedAt(v int64) {
	o.UpdatedAt = &v
}

// GetCustomerInfo returns the CustomerInfo field value if set, zero value otherwise.
func (o *OrderResponse) GetCustomerInfo() OrderResponseCustomerInfo {
	if o == nil || IsNil(o.CustomerInfo) {
		var ret OrderResponseCustomerInfo
		return ret
	}
	return *o.CustomerInfo
}

// GetCustomerInfoOk returns a tuple with the CustomerInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetCustomerInfoOk() (*OrderResponseCustomerInfo, bool) {
	if o == nil || IsNil(o.CustomerInfo) {
		return nil, false
	}
	return o.CustomerInfo, true
}

// HasCustomerInfo returns a boolean if a field has been set.
func (o *OrderResponse) HasCustomerInfo() bool {
	if o != nil && !IsNil(o.CustomerInfo) {
		return true
	}

	return false
}

// SetCustomerInfo gets a reference to the given OrderResponseCustomerInfo and assigns it to the CustomerInfo field.
func (o *OrderResponse) SetCustomerInfo(v OrderResponseCustomerInfo) {
	o.CustomerInfo = &v
}

// GetShippingContact returns the ShippingContact field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderResponse) GetShippingContact() OrderResponseShippingContact {
	if o == nil || IsNil(o.ShippingContact.Get()) {
		var ret OrderResponseShippingContact
		return ret
	}
	return *o.ShippingContact.Get()
}

// GetShippingContactOk returns a tuple with the ShippingContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderResponse) GetShippingContactOk() (*OrderResponseShippingContact, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShippingContact.Get(), o.ShippingContact.IsSet()
}

// HasShippingContact returns a boolean if a field has been set.
func (o *OrderResponse) HasShippingContact() bool {
	if o != nil && o.ShippingContact.IsSet() {
		return true
	}

	return false
}

// SetShippingContact gets a reference to the given NullableOrderResponseShippingContact and assigns it to the ShippingContact field.
func (o *OrderResponse) SetShippingContact(v OrderResponseShippingContact) {
	o.ShippingContact.Set(&v)
}
// SetShippingContactNil sets the value for ShippingContact to be an explicit nil
func (o *OrderResponse) SetShippingContactNil() {
	o.ShippingContact.Set(nil)
}

// UnsetShippingContact ensures that no value is present for ShippingContact, not even an explicit nil
func (o *OrderResponse) UnsetShippingContact() {
	o.ShippingContact.Unset()
}

// GetChannel returns the Channel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderResponse) GetChannel() OrderResponseChannel {
	if o == nil || IsNil(o.Channel.Get()) {
		var ret OrderResponseChannel
		return ret
	}
	return *o.Channel.Get()
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderResponse) GetChannelOk() (*OrderResponseChannel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channel.Get(), o.Channel.IsSet()
}

// HasChannel returns a boolean if a field has been set.
func (o *OrderResponse) HasChannel() bool {
	if o != nil && o.Channel.IsSet() {
		return true
	}

	return false
}

// SetChannel gets a reference to the given NullableOrderResponseChannel and assigns it to the Channel field.
func (o *OrderResponse) SetChannel(v OrderResponseChannel) {
	o.Channel.Set(&v)
}
// SetChannelNil sets the value for Channel to be an explicit nil
func (o *OrderResponse) SetChannelNil() {
	o.Channel.Set(nil)
}

// UnsetChannel ensures that no value is present for Channel, not even an explicit nil
func (o *OrderResponse) UnsetChannel() {
	o.Channel.Unset()
}

// GetFiscalEntity returns the FiscalEntity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderResponse) GetFiscalEntity() OrderFiscalEntityResponse {
	if o == nil || IsNil(o.FiscalEntity.Get()) {
		var ret OrderFiscalEntityResponse
		return ret
	}
	return *o.FiscalEntity.Get()
}

// GetFiscalEntityOk returns a tuple with the FiscalEntity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderResponse) GetFiscalEntityOk() (*OrderFiscalEntityResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.FiscalEntity.Get(), o.FiscalEntity.IsSet()
}

// HasFiscalEntity returns a boolean if a field has been set.
func (o *OrderResponse) HasFiscalEntity() bool {
	if o != nil && o.FiscalEntity.IsSet() {
		return true
	}

	return false
}

// SetFiscalEntity gets a reference to the given NullableOrderFiscalEntityResponse and assigns it to the FiscalEntity field.
func (o *OrderResponse) SetFiscalEntity(v OrderFiscalEntityResponse) {
	o.FiscalEntity.Set(&v)
}
// SetFiscalEntityNil sets the value for FiscalEntity to be an explicit nil
func (o *OrderResponse) SetFiscalEntityNil() {
	o.FiscalEntity.Set(nil)
}

// UnsetFiscalEntity ensures that no value is present for FiscalEntity, not even an explicit nil
func (o *OrderResponse) UnsetFiscalEntity() {
	o.FiscalEntity.Unset()
}

// GetCheckout returns the Checkout field value if set, zero value otherwise.
func (o *OrderResponse) GetCheckout() OrderResponseCheckout {
	if o == nil || IsNil(o.Checkout) {
		var ret OrderResponseCheckout
		return ret
	}
	return *o.Checkout
}

// GetCheckoutOk returns a tuple with the Checkout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetCheckoutOk() (*OrderResponseCheckout, bool) {
	if o == nil || IsNil(o.Checkout) {
		return nil, false
	}
	return o.Checkout, true
}

// HasCheckout returns a boolean if a field has been set.
func (o *OrderResponse) HasCheckout() bool {
	if o != nil && !IsNil(o.Checkout) {
		return true
	}

	return false
}

// SetCheckout gets a reference to the given OrderResponseCheckout and assigns it to the Checkout field.
func (o *OrderResponse) SetCheckout(v OrderResponseCheckout) {
	o.Checkout = &v
}

// GetLineItems returns the LineItems field value if set, zero value otherwise.
func (o *OrderResponse) GetLineItems() OrderResponseProducts {
	if o == nil || IsNil(o.LineItems) {
		var ret OrderResponseProducts
		return ret
	}
	return *o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetLineItemsOk() (*OrderResponseProducts, bool) {
	if o == nil || IsNil(o.LineItems) {
		return nil, false
	}
	return o.LineItems, true
}

// HasLineItems returns a boolean if a field has been set.
func (o *OrderResponse) HasLineItems() bool {
	if o != nil && !IsNil(o.LineItems) {
		return true
	}

	return false
}

// SetLineItems gets a reference to the given OrderResponseProducts and assigns it to the LineItems field.
func (o *OrderResponse) SetLineItems(v OrderResponseProducts) {
	o.LineItems = &v
}

// GetDiscountLines returns the DiscountLines field value if set, zero value otherwise.
func (o *OrderResponse) GetDiscountLines() OrderResponseDiscountLines {
	if o == nil || IsNil(o.DiscountLines) {
		var ret OrderResponseDiscountLines
		return ret
	}
	return *o.DiscountLines
}

// GetDiscountLinesOk returns a tuple with the DiscountLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetDiscountLinesOk() (*OrderResponseDiscountLines, bool) {
	if o == nil || IsNil(o.DiscountLines) {
		return nil, false
	}
	return o.DiscountLines, true
}

// HasDiscountLines returns a boolean if a field has been set.
func (o *OrderResponse) HasDiscountLines() bool {
	if o != nil && !IsNil(o.DiscountLines) {
		return true
	}

	return false
}

// SetDiscountLines gets a reference to the given OrderResponseDiscountLines and assigns it to the DiscountLines field.
func (o *OrderResponse) SetDiscountLines(v OrderResponseDiscountLines) {
	o.DiscountLines = &v
}

// GetCharges returns the Charges field value if set, zero value otherwise.
func (o *OrderResponse) GetCharges() OrderResponseCharges {
	if o == nil || IsNil(o.Charges) {
		var ret OrderResponseCharges
		return ret
	}
	return *o.Charges
}

// GetChargesOk returns a tuple with the Charges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderResponse) GetChargesOk() (*OrderResponseCharges, bool) {
	if o == nil || IsNil(o.Charges) {
		return nil, false
	}
	return o.Charges, true
}

// HasCharges returns a boolean if a field has been set.
func (o *OrderResponse) HasCharges() bool {
	if o != nil && !IsNil(o.Charges) {
		return true
	}

	return false
}

// SetCharges gets a reference to the given OrderResponseCharges and assigns it to the Charges field.
func (o *OrderResponse) SetCharges(v OrderResponseCharges) {
	o.Charges = &v
}

// GetPartialReference returns the PartialReference field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderResponse) GetPartialReference() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.PartialReference
}

// GetPartialReferenceOk returns a tuple with the PartialReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderResponse) GetPartialReferenceOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PartialReference) {
		return map[string]interface{}{}, false
	}
	return o.PartialReference, true
}

// HasPartialReference returns a boolean if a field has been set.
func (o *OrderResponse) HasPartialReference() bool {
	if o != nil && !IsNil(o.PartialReference) {
		return true
	}

	return false
}

// SetPartialReference gets a reference to the given map[string]interface{} and assigns it to the PartialReference field.
func (o *OrderResponse) SetPartialReference(v map[string]interface{}) {
	o.PartialReference = v
}

// GetPaymentsInfo returns the PaymentsInfo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderResponse) GetPaymentsInfo() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.PaymentsInfo
}

// GetPaymentsInfoOk returns a tuple with the PaymentsInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderResponse) GetPaymentsInfoOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PaymentsInfo) {
		return map[string]interface{}{}, false
	}
	return o.PaymentsInfo, true
}

// HasPaymentsInfo returns a boolean if a field has been set.
func (o *OrderResponse) HasPaymentsInfo() bool {
	if o != nil && !IsNil(o.PaymentsInfo) {
		return true
	}

	return false
}

// SetPaymentsInfo gets a reference to the given map[string]interface{} and assigns it to the PaymentsInfo field.
func (o *OrderResponse) SetPaymentsInfo(v map[string]interface{}) {
	o.PaymentsInfo = v
}

func (o OrderResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.Livemode) {
		toSerialize["livemode"] = o.Livemode
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if o.PaymentStatus.IsSet() {
		toSerialize["payment_status"] = o.PaymentStatus.Get()
	}
	if !IsNil(o.AmountRefunded) {
		toSerialize["amount_refunded"] = o.AmountRefunded
	}
	if o.SplitPayment.IsSet() {
		toSerialize["split_payment"] = o.SplitPayment.Get()
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.IsRefundable) {
		toSerialize["is_refundable"] = o.IsRefundable
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.CustomerInfo) {
		toSerialize["customer_info"] = o.CustomerInfo
	}
	if o.ShippingContact.IsSet() {
		toSerialize["shipping_contact"] = o.ShippingContact.Get()
	}
	if o.Channel.IsSet() {
		toSerialize["channel"] = o.Channel.Get()
	}
	if o.FiscalEntity.IsSet() {
		toSerialize["fiscal_entity"] = o.FiscalEntity.Get()
	}
	if !IsNil(o.Checkout) {
		toSerialize["checkout"] = o.Checkout
	}
	if !IsNil(o.LineItems) {
		toSerialize["line_items"] = o.LineItems
	}
	if !IsNil(o.DiscountLines) {
		toSerialize["discount_lines"] = o.DiscountLines
	}
	if !IsNil(o.Charges) {
		toSerialize["charges"] = o.Charges
	}
	if o.PartialReference != nil {
		toSerialize["partial_reference"] = o.PartialReference
	}
	if o.PaymentsInfo != nil {
		toSerialize["payments_info"] = o.PaymentsInfo
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderResponse) UnmarshalJSON(data []byte) (err error) {
	varOrderResponse := _OrderResponse{}

	err = json.Unmarshal(data, &varOrderResponse)

	if err != nil {
		return err
	}

	*o = OrderResponse(varOrderResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object")
		delete(additionalProperties, "livemode")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "payment_status")
		delete(additionalProperties, "amount_refunded")
		delete(additionalProperties, "split_payment")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "is_refundable")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "customer_info")
		delete(additionalProperties, "shipping_contact")
		delete(additionalProperties, "channel")
		delete(additionalProperties, "fiscal_entity")
		delete(additionalProperties, "checkout")
		delete(additionalProperties, "line_items")
		delete(additionalProperties, "discount_lines")
		delete(additionalProperties, "charges")
		delete(additionalProperties, "partial_reference")
		delete(additionalProperties, "payments_info")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrderResponse struct {
	value *OrderResponse
	isSet bool
}

func (v NullableOrderResponse) Get() *OrderResponse {
	return v.value
}

func (v *NullableOrderResponse) Set(val *OrderResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderResponse(val *OrderResponse) *NullableOrderResponse {
	return &NullableOrderResponse{value: val, isSet: true}
}

func (v NullableOrderResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


