/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
	"fmt"
)

// checks if the ChargesDataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChargesDataResponse{}

// ChargesDataResponse struct for ChargesDataResponse
type ChargesDataResponse struct {
	Id string `json:"id"`
	Livemode bool `json:"livemode"`
	CreatedAt int64 `json:"created_at"`
	Currency string `json:"currency"`
	FailureCode NullableString `json:"failure_code,omitempty"`
	FailureMessage NullableString `json:"failure_message,omitempty"`
	Channel *ChargeResponseChannel `json:"channel,omitempty"`
	PaymentMethod ChargeResponsePaymentMethod `json:"payment_method"`
	Object string `json:"object"`
	DeviceFingerprint *string `json:"device_fingerprint,omitempty"`
	Description *string `json:"description,omitempty"`
	IsRefundable *bool `json:"is_refundable,omitempty"`
	ReferenceId NullableString `json:"reference_id,omitempty"`
	Status string `json:"status"`
	Amount int64 `json:"amount"`
	PaidAt NullableInt64 `json:"paid_at,omitempty"`
	CustomerId *string `json:"customer_id,omitempty"`
	OrderId *string `json:"order_id,omitempty"`
	Refunds NullableChargeResponseRefunds `json:"refunds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChargesDataResponse ChargesDataResponse

// NewChargesDataResponse instantiates a new ChargesDataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChargesDataResponse(id string, livemode bool, createdAt int64, currency string, paymentMethod ChargeResponsePaymentMethod, object string, status string, amount int64) *ChargesDataResponse {
	this := ChargesDataResponse{}
	this.Id = id
	this.Livemode = livemode
	this.CreatedAt = createdAt
	this.Currency = currency
	this.PaymentMethod = paymentMethod
	this.Object = object
	this.Status = status
	this.Amount = amount
	return &this
}

// NewChargesDataResponseWithDefaults instantiates a new ChargesDataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChargesDataResponseWithDefaults() *ChargesDataResponse {
	this := ChargesDataResponse{}
	return &this
}

// GetId returns the Id field value
func (o *ChargesDataResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChargesDataResponse) SetId(v string) {
	o.Id = v
}

// GetLivemode returns the Livemode field value
func (o *ChargesDataResponse) GetLivemode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetLivemodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livemode, true
}

// SetLivemode sets field value
func (o *ChargesDataResponse) SetLivemode(v bool) {
	o.Livemode = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ChargesDataResponse) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ChargesDataResponse) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetCurrency returns the Currency field value
func (o *ChargesDataResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *ChargesDataResponse) SetCurrency(v string) {
	o.Currency = v
}

// GetFailureCode returns the FailureCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChargesDataResponse) GetFailureCode() string {
	if o == nil || IsNil(o.FailureCode.Get()) {
		var ret string
		return ret
	}
	return *o.FailureCode.Get()
}

// GetFailureCodeOk returns a tuple with the FailureCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChargesDataResponse) GetFailureCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailureCode.Get(), o.FailureCode.IsSet()
}

// HasFailureCode returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasFailureCode() bool {
	if o != nil && o.FailureCode.IsSet() {
		return true
	}

	return false
}

// SetFailureCode gets a reference to the given NullableString and assigns it to the FailureCode field.
func (o *ChargesDataResponse) SetFailureCode(v string) {
	o.FailureCode.Set(&v)
}
// SetFailureCodeNil sets the value for FailureCode to be an explicit nil
func (o *ChargesDataResponse) SetFailureCodeNil() {
	o.FailureCode.Set(nil)
}

// UnsetFailureCode ensures that no value is present for FailureCode, not even an explicit nil
func (o *ChargesDataResponse) UnsetFailureCode() {
	o.FailureCode.Unset()
}

// GetFailureMessage returns the FailureMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChargesDataResponse) GetFailureMessage() string {
	if o == nil || IsNil(o.FailureMessage.Get()) {
		var ret string
		return ret
	}
	return *o.FailureMessage.Get()
}

// GetFailureMessageOk returns a tuple with the FailureMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChargesDataResponse) GetFailureMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FailureMessage.Get(), o.FailureMessage.IsSet()
}

// HasFailureMessage returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasFailureMessage() bool {
	if o != nil && o.FailureMessage.IsSet() {
		return true
	}

	return false
}

// SetFailureMessage gets a reference to the given NullableString and assigns it to the FailureMessage field.
func (o *ChargesDataResponse) SetFailureMessage(v string) {
	o.FailureMessage.Set(&v)
}
// SetFailureMessageNil sets the value for FailureMessage to be an explicit nil
func (o *ChargesDataResponse) SetFailureMessageNil() {
	o.FailureMessage.Set(nil)
}

// UnsetFailureMessage ensures that no value is present for FailureMessage, not even an explicit nil
func (o *ChargesDataResponse) UnsetFailureMessage() {
	o.FailureMessage.Unset()
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *ChargesDataResponse) GetChannel() ChargeResponseChannel {
	if o == nil || IsNil(o.Channel) {
		var ret ChargeResponseChannel
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetChannelOk() (*ChargeResponseChannel, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given ChargeResponseChannel and assigns it to the Channel field.
func (o *ChargesDataResponse) SetChannel(v ChargeResponseChannel) {
	o.Channel = &v
}

// GetPaymentMethod returns the PaymentMethod field value
func (o *ChargesDataResponse) GetPaymentMethod() ChargeResponsePaymentMethod {
	if o == nil {
		var ret ChargeResponsePaymentMethod
		return ret
	}

	return o.PaymentMethod
}

// GetPaymentMethodOk returns a tuple with the PaymentMethod field value
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetPaymentMethodOk() (*ChargeResponsePaymentMethod, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaymentMethod, true
}

// SetPaymentMethod sets field value
func (o *ChargesDataResponse) SetPaymentMethod(v ChargeResponsePaymentMethod) {
	o.PaymentMethod = v
}

// GetObject returns the Object field value
func (o *ChargesDataResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *ChargesDataResponse) SetObject(v string) {
	o.Object = v
}

// GetDeviceFingerprint returns the DeviceFingerprint field value if set, zero value otherwise.
func (o *ChargesDataResponse) GetDeviceFingerprint() string {
	if o == nil || IsNil(o.DeviceFingerprint) {
		var ret string
		return ret
	}
	return *o.DeviceFingerprint
}

// GetDeviceFingerprintOk returns a tuple with the DeviceFingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetDeviceFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.DeviceFingerprint) {
		return nil, false
	}
	return o.DeviceFingerprint, true
}

// HasDeviceFingerprint returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasDeviceFingerprint() bool {
	if o != nil && !IsNil(o.DeviceFingerprint) {
		return true
	}

	return false
}

// SetDeviceFingerprint gets a reference to the given string and assigns it to the DeviceFingerprint field.
func (o *ChargesDataResponse) SetDeviceFingerprint(v string) {
	o.DeviceFingerprint = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ChargesDataResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ChargesDataResponse) SetDescription(v string) {
	o.Description = &v
}

// GetIsRefundable returns the IsRefundable field value if set, zero value otherwise.
func (o *ChargesDataResponse) GetIsRefundable() bool {
	if o == nil || IsNil(o.IsRefundable) {
		var ret bool
		return ret
	}
	return *o.IsRefundable
}

// GetIsRefundableOk returns a tuple with the IsRefundable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetIsRefundableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsRefundable) {
		return nil, false
	}
	return o.IsRefundable, true
}

// HasIsRefundable returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasIsRefundable() bool {
	if o != nil && !IsNil(o.IsRefundable) {
		return true
	}

	return false
}

// SetIsRefundable gets a reference to the given bool and assigns it to the IsRefundable field.
func (o *ChargesDataResponse) SetIsRefundable(v bool) {
	o.IsRefundable = &v
}

// GetReferenceId returns the ReferenceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChargesDataResponse) GetReferenceId() string {
	if o == nil || IsNil(o.ReferenceId.Get()) {
		var ret string
		return ret
	}
	return *o.ReferenceId.Get()
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChargesDataResponse) GetReferenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReferenceId.Get(), o.ReferenceId.IsSet()
}

// HasReferenceId returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasReferenceId() bool {
	if o != nil && o.ReferenceId.IsSet() {
		return true
	}

	return false
}

// SetReferenceId gets a reference to the given NullableString and assigns it to the ReferenceId field.
func (o *ChargesDataResponse) SetReferenceId(v string) {
	o.ReferenceId.Set(&v)
}
// SetReferenceIdNil sets the value for ReferenceId to be an explicit nil
func (o *ChargesDataResponse) SetReferenceIdNil() {
	o.ReferenceId.Set(nil)
}

// UnsetReferenceId ensures that no value is present for ReferenceId, not even an explicit nil
func (o *ChargesDataResponse) UnsetReferenceId() {
	o.ReferenceId.Unset()
}

// GetStatus returns the Status field value
func (o *ChargesDataResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ChargesDataResponse) SetStatus(v string) {
	o.Status = v
}

// GetAmount returns the Amount field value
func (o *ChargesDataResponse) GetAmount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetAmountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ChargesDataResponse) SetAmount(v int64) {
	o.Amount = v
}

// GetPaidAt returns the PaidAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChargesDataResponse) GetPaidAt() int64 {
	if o == nil || IsNil(o.PaidAt.Get()) {
		var ret int64
		return ret
	}
	return *o.PaidAt.Get()
}

// GetPaidAtOk returns a tuple with the PaidAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChargesDataResponse) GetPaidAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.PaidAt.Get(), o.PaidAt.IsSet()
}

// HasPaidAt returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasPaidAt() bool {
	if o != nil && o.PaidAt.IsSet() {
		return true
	}

	return false
}

// SetPaidAt gets a reference to the given NullableInt64 and assigns it to the PaidAt field.
func (o *ChargesDataResponse) SetPaidAt(v int64) {
	o.PaidAt.Set(&v)
}
// SetPaidAtNil sets the value for PaidAt to be an explicit nil
func (o *ChargesDataResponse) SetPaidAtNil() {
	o.PaidAt.Set(nil)
}

// UnsetPaidAt ensures that no value is present for PaidAt, not even an explicit nil
func (o *ChargesDataResponse) UnsetPaidAt() {
	o.PaidAt.Unset()
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *ChargesDataResponse) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *ChargesDataResponse) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *ChargesDataResponse) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChargesDataResponse) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *ChargesDataResponse) SetOrderId(v string) {
	o.OrderId = &v
}

// GetRefunds returns the Refunds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChargesDataResponse) GetRefunds() ChargeResponseRefunds {
	if o == nil || IsNil(o.Refunds.Get()) {
		var ret ChargeResponseRefunds
		return ret
	}
	return *o.Refunds.Get()
}

// GetRefundsOk returns a tuple with the Refunds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChargesDataResponse) GetRefundsOk() (*ChargeResponseRefunds, bool) {
	if o == nil {
		return nil, false
	}
	return o.Refunds.Get(), o.Refunds.IsSet()
}

// HasRefunds returns a boolean if a field has been set.
func (o *ChargesDataResponse) HasRefunds() bool {
	if o != nil && o.Refunds.IsSet() {
		return true
	}

	return false
}

// SetRefunds gets a reference to the given NullableChargeResponseRefunds and assigns it to the Refunds field.
func (o *ChargesDataResponse) SetRefunds(v ChargeResponseRefunds) {
	o.Refunds.Set(&v)
}
// SetRefundsNil sets the value for Refunds to be an explicit nil
func (o *ChargesDataResponse) SetRefundsNil() {
	o.Refunds.Set(nil)
}

// UnsetRefunds ensures that no value is present for Refunds, not even an explicit nil
func (o *ChargesDataResponse) UnsetRefunds() {
	o.Refunds.Unset()
}

func (o ChargesDataResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChargesDataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["livemode"] = o.Livemode
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["currency"] = o.Currency
	if o.FailureCode.IsSet() {
		toSerialize["failure_code"] = o.FailureCode.Get()
	}
	if o.FailureMessage.IsSet() {
		toSerialize["failure_message"] = o.FailureMessage.Get()
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	toSerialize["payment_method"] = o.PaymentMethod
	toSerialize["object"] = o.Object
	if !IsNil(o.DeviceFingerprint) {
		toSerialize["device_fingerprint"] = o.DeviceFingerprint
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IsRefundable) {
		toSerialize["is_refundable"] = o.IsRefundable
	}
	if o.ReferenceId.IsSet() {
		toSerialize["reference_id"] = o.ReferenceId.Get()
	}
	toSerialize["status"] = o.Status
	toSerialize["amount"] = o.Amount
	if o.PaidAt.IsSet() {
		toSerialize["paid_at"] = o.PaidAt.Get()
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	if !IsNil(o.OrderId) {
		toSerialize["order_id"] = o.OrderId
	}
	if o.Refunds.IsSet() {
		toSerialize["refunds"] = o.Refunds.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChargesDataResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"livemode",
		"created_at",
		"currency",
		"payment_method",
		"object",
		"status",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChargesDataResponse := _ChargesDataResponse{}

	err = json.Unmarshal(data, &varChargesDataResponse)

	if err != nil {
		return err
	}

	*o = ChargesDataResponse(varChargesDataResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "livemode")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "currency")
		delete(additionalProperties, "failure_code")
		delete(additionalProperties, "failure_message")
		delete(additionalProperties, "channel")
		delete(additionalProperties, "payment_method")
		delete(additionalProperties, "object")
		delete(additionalProperties, "device_fingerprint")
		delete(additionalProperties, "description")
		delete(additionalProperties, "is_refundable")
		delete(additionalProperties, "reference_id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "amount")
		delete(additionalProperties, "paid_at")
		delete(additionalProperties, "customer_id")
		delete(additionalProperties, "order_id")
		delete(additionalProperties, "refunds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChargesDataResponse struct {
	value *ChargesDataResponse
	isSet bool
}

func (v NullableChargesDataResponse) Get() *ChargesDataResponse {
	return v.value
}

func (v *NullableChargesDataResponse) Set(val *ChargesDataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChargesDataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChargesDataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChargesDataResponse(val *ChargesDataResponse) *NullableChargesDataResponse {
	return &NullableChargesDataResponse{value: val, isSet: true}
}

func (v NullableChargesDataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChargesDataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


