/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomerPaymentMethodCashResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerPaymentMethodCashResponse{}

// CustomerPaymentMethodCashResponse Cash payment method response.
type CustomerPaymentMethodCashResponse struct {
	Id string `json:"id"`
	Object string `json:"object"`
	CreatedAt int64 `json:"created_at"`
	// Customer ID this payment source belongs to.
	ParentId NullableString `json:"parent_id,omitempty"`
	// Payment method type.
	Type string `json:"type"`
	Reference *string `json:"reference,omitempty"`
	Barcode *string `json:"barcode,omitempty"`
	BarcodeUrl *string `json:"barcode_url,omitempty"`
	ExpiresAt NullableInt64 `json:"expires_at,omitempty"`
	Provider *string `json:"provider,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerPaymentMethodCashResponse CustomerPaymentMethodCashResponse

// NewCustomerPaymentMethodCashResponse instantiates a new CustomerPaymentMethodCashResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerPaymentMethodCashResponse(id string, object string, createdAt int64, type_ string) *CustomerPaymentMethodCashResponse {
	this := CustomerPaymentMethodCashResponse{}
	this.Id = id
	this.Object = object
	this.CreatedAt = createdAt
	this.Type = type_
	return &this
}

// NewCustomerPaymentMethodCashResponseWithDefaults instantiates a new CustomerPaymentMethodCashResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerPaymentMethodCashResponseWithDefaults() *CustomerPaymentMethodCashResponse {
	this := CustomerPaymentMethodCashResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CustomerPaymentMethodCashResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodCashResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomerPaymentMethodCashResponse) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value
func (o *CustomerPaymentMethodCashResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodCashResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *CustomerPaymentMethodCashResponse) SetObject(v string) {
	o.Object = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CustomerPaymentMethodCashResponse) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodCashResponse) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CustomerPaymentMethodCashResponse) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetParentId returns the ParentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerPaymentMethodCashResponse) GetParentId() string {
	if o == nil || IsNil(o.ParentId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentId.Get()
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerPaymentMethodCashResponse) GetParentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentId.Get(), o.ParentId.IsSet()
}

// HasParentId returns a boolean if a field has been set.
func (o *CustomerPaymentMethodCashResponse) HasParentId() bool {
	if o != nil && o.ParentId.IsSet() {
		return true
	}

	return false
}

// SetParentId gets a reference to the given NullableString and assigns it to the ParentId field.
func (o *CustomerPaymentMethodCashResponse) SetParentId(v string) {
	o.ParentId.Set(&v)
}
// SetParentIdNil sets the value for ParentId to be an explicit nil
func (o *CustomerPaymentMethodCashResponse) SetParentIdNil() {
	o.ParentId.Set(nil)
}

// UnsetParentId ensures that no value is present for ParentId, not even an explicit nil
func (o *CustomerPaymentMethodCashResponse) UnsetParentId() {
	o.ParentId.Unset()
}

// GetType returns the Type field value
func (o *CustomerPaymentMethodCashResponse) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodCashResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CustomerPaymentMethodCashResponse) SetType(v string) {
	o.Type = v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *CustomerPaymentMethodCashResponse) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodCashResponse) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *CustomerPaymentMethodCashResponse) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *CustomerPaymentMethodCashResponse) SetReference(v string) {
	o.Reference = &v
}

// GetBarcode returns the Barcode field value if set, zero value otherwise.
func (o *CustomerPaymentMethodCashResponse) GetBarcode() string {
	if o == nil || IsNil(o.Barcode) {
		var ret string
		return ret
	}
	return *o.Barcode
}

// GetBarcodeOk returns a tuple with the Barcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodCashResponse) GetBarcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Barcode) {
		return nil, false
	}
	return o.Barcode, true
}

// HasBarcode returns a boolean if a field has been set.
func (o *CustomerPaymentMethodCashResponse) HasBarcode() bool {
	if o != nil && !IsNil(o.Barcode) {
		return true
	}

	return false
}

// SetBarcode gets a reference to the given string and assigns it to the Barcode field.
func (o *CustomerPaymentMethodCashResponse) SetBarcode(v string) {
	o.Barcode = &v
}

// GetBarcodeUrl returns the BarcodeUrl field value if set, zero value otherwise.
func (o *CustomerPaymentMethodCashResponse) GetBarcodeUrl() string {
	if o == nil || IsNil(o.BarcodeUrl) {
		var ret string
		return ret
	}
	return *o.BarcodeUrl
}

// GetBarcodeUrlOk returns a tuple with the BarcodeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodCashResponse) GetBarcodeUrlOk() (*string, bool) {
	if o == nil || IsNil(o.BarcodeUrl) {
		return nil, false
	}
	return o.BarcodeUrl, true
}

// HasBarcodeUrl returns a boolean if a field has been set.
func (o *CustomerPaymentMethodCashResponse) HasBarcodeUrl() bool {
	if o != nil && !IsNil(o.BarcodeUrl) {
		return true
	}

	return false
}

// SetBarcodeUrl gets a reference to the given string and assigns it to the BarcodeUrl field.
func (o *CustomerPaymentMethodCashResponse) SetBarcodeUrl(v string) {
	o.BarcodeUrl = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerPaymentMethodCashResponse) GetExpiresAt() int64 {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret int64
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerPaymentMethodCashResponse) GetExpiresAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *CustomerPaymentMethodCashResponse) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableInt64 and assigns it to the ExpiresAt field.
func (o *CustomerPaymentMethodCashResponse) SetExpiresAt(v int64) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *CustomerPaymentMethodCashResponse) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *CustomerPaymentMethodCashResponse) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *CustomerPaymentMethodCashResponse) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPaymentMethodCashResponse) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *CustomerPaymentMethodCashResponse) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *CustomerPaymentMethodCashResponse) SetProvider(v string) {
	o.Provider = &v
}

func (o CustomerPaymentMethodCashResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerPaymentMethodCashResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["object"] = o.Object
	toSerialize["created_at"] = o.CreatedAt
	if o.ParentId.IsSet() {
		toSerialize["parent_id"] = o.ParentId.Get()
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.Barcode) {
		toSerialize["barcode"] = o.Barcode
	}
	if !IsNil(o.BarcodeUrl) {
		toSerialize["barcode_url"] = o.BarcodeUrl
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerPaymentMethodCashResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"object",
		"created_at",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerPaymentMethodCashResponse := _CustomerPaymentMethodCashResponse{}

	err = json.Unmarshal(data, &varCustomerPaymentMethodCashResponse)

	if err != nil {
		return err
	}

	*o = CustomerPaymentMethodCashResponse(varCustomerPaymentMethodCashResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "parent_id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "reference")
		delete(additionalProperties, "barcode")
		delete(additionalProperties, "barcode_url")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "provider")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerPaymentMethodCashResponse struct {
	value *CustomerPaymentMethodCashResponse
	isSet bool
}

func (v NullableCustomerPaymentMethodCashResponse) Get() *CustomerPaymentMethodCashResponse {
	return v.value
}

func (v *NullableCustomerPaymentMethodCashResponse) Set(val *CustomerPaymentMethodCashResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerPaymentMethodCashResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerPaymentMethodCashResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerPaymentMethodCashResponse(val *CustomerPaymentMethodCashResponse) *NullableCustomerPaymentMethodCashResponse {
	return &NullableCustomerPaymentMethodCashResponse{value: val, isSet: true}
}

func (v NullableCustomerPaymentMethodCashResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerPaymentMethodCashResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


