/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
	"fmt"
)

// CustomerPaymentSourcesInner - struct for CustomerPaymentSourcesInner
type CustomerPaymentSourcesInner struct {
	PaymentMethodCashRequest *PaymentMethodCashRequest
}

// PaymentMethodCashRequestAsCustomerPaymentSourcesInner is a convenience function that returns PaymentMethodCashRequest wrapped in CustomerPaymentSourcesInner
func PaymentMethodCashRequestAsCustomerPaymentSourcesInner(v *PaymentMethodCashRequest) CustomerPaymentSourcesInner {
	return CustomerPaymentSourcesInner{
		PaymentMethodCashRequest: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CustomerPaymentSourcesInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PaymentMethodCashRequest
	err = json.Unmarshal(data, &dst.PaymentMethodCashRequest)
	if err == nil {
		jsonPaymentMethodCashRequest, _ := json.Marshal(dst.PaymentMethodCashRequest)
		if string(jsonPaymentMethodCashRequest) == "{}" { // empty struct
			dst.PaymentMethodCashRequest = nil
		} else {
			match++
		}
	} else {
		dst.PaymentMethodCashRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PaymentMethodCashRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CustomerPaymentSourcesInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CustomerPaymentSourcesInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CustomerPaymentSourcesInner) MarshalJSON() ([]byte, error) {
	if src.PaymentMethodCashRequest != nil {
		return json.Marshal(&src.PaymentMethodCashRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CustomerPaymentSourcesInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PaymentMethodCashRequest != nil {
		return obj.PaymentMethodCashRequest
	}

	// all schemas are nil
	return nil
}

type NullableCustomerPaymentSourcesInner struct {
	value *CustomerPaymentSourcesInner
	isSet bool
}

func (v NullableCustomerPaymentSourcesInner) Get() *CustomerPaymentSourcesInner {
	return v.value
}

func (v *NullableCustomerPaymentSourcesInner) Set(val *CustomerPaymentSourcesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerPaymentSourcesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerPaymentSourcesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerPaymentSourcesInner(val *CustomerPaymentSourcesInner) *NullableCustomerPaymentSourcesInner {
	return &NullableCustomerPaymentSourcesInner{value: val, isSet: true}
}

func (v NullableCustomerPaymentSourcesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerPaymentSourcesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


