/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
	"fmt"
)

// checks if the WebhookResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookResponse{}

// WebhookResponse Represents a webhook endpoint configured to receive event notifications.
type WebhookResponse struct {
	// Unique identifier of the webhook.
	Id string `json:"id"`
	// Object name, which is webhook.
	Object string `json:"object"`
	// The URL where events will be delivered.
	Url string `json:"url"`
	// Current delivery status of the webhook.
	Status string `json:"status"`
	// List of event types the webhook is subscribed to.
	SubscribedEvents []string `json:"subscribed_events"`
	// Indicates whether the webhook uses synchronous delivery behavior.
	Synchronous bool `json:"synchronous"`
	// Optional description of the webhook.
	Description NullableString `json:"description,omitempty"`
	// Indicates whether the webhook is in live mode or test mode.
	Livemode bool `json:"livemode"`
	// Indicates whether the webhook is active.
	Active bool `json:"active"`
	AdditionalProperties map[string]interface{}
}

type _WebhookResponse WebhookResponse

// NewWebhookResponse instantiates a new WebhookResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookResponse(id string, object string, url string, status string, subscribedEvents []string, synchronous bool, livemode bool, active bool) *WebhookResponse {
	this := WebhookResponse{}
	this.Id = id
	this.Object = object
	this.Url = url
	this.Status = status
	this.SubscribedEvents = subscribedEvents
	this.Synchronous = synchronous
	this.Livemode = livemode
	this.Active = active
	return &this
}

// NewWebhookResponseWithDefaults instantiates a new WebhookResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookResponseWithDefaults() *WebhookResponse {
	this := WebhookResponse{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookResponse) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value
func (o *WebhookResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *WebhookResponse) SetObject(v string) {
	o.Object = v
}

// GetUrl returns the Url field value
func (o *WebhookResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookResponse) SetUrl(v string) {
	o.Url = v
}

// GetStatus returns the Status field value
func (o *WebhookResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WebhookResponse) SetStatus(v string) {
	o.Status = v
}

// GetSubscribedEvents returns the SubscribedEvents field value
func (o *WebhookResponse) GetSubscribedEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SubscribedEvents
}

// GetSubscribedEventsOk returns a tuple with the SubscribedEvents field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetSubscribedEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubscribedEvents, true
}

// SetSubscribedEvents sets field value
func (o *WebhookResponse) SetSubscribedEvents(v []string) {
	o.SubscribedEvents = v
}

// GetSynchronous returns the Synchronous field value
func (o *WebhookResponse) GetSynchronous() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Synchronous
}

// GetSynchronousOk returns a tuple with the Synchronous field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetSynchronousOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Synchronous, true
}

// SetSynchronous sets field value
func (o *WebhookResponse) SetSynchronous(v bool) {
	o.Synchronous = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookResponse) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *WebhookResponse) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *WebhookResponse) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *WebhookResponse) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *WebhookResponse) UnsetDescription() {
	o.Description.Unset()
}

// GetLivemode returns the Livemode field value
func (o *WebhookResponse) GetLivemode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetLivemodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livemode, true
}

// SetLivemode sets field value
func (o *WebhookResponse) SetLivemode(v bool) {
	o.Livemode = v
}

// GetActive returns the Active field value
func (o *WebhookResponse) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *WebhookResponse) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *WebhookResponse) SetActive(v bool) {
	o.Active = v
}

func (o WebhookResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["object"] = o.Object
	toSerialize["url"] = o.Url
	toSerialize["status"] = o.Status
	toSerialize["subscribed_events"] = o.SubscribedEvents
	toSerialize["synchronous"] = o.Synchronous
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	toSerialize["livemode"] = o.Livemode
	toSerialize["active"] = o.Active

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"object",
		"url",
		"status",
		"subscribed_events",
		"synchronous",
		"livemode",
		"active",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookResponse := _WebhookResponse{}

	err = json.Unmarshal(data, &varWebhookResponse)

	if err != nil {
		return err
	}

	*o = WebhookResponse(varWebhookResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object")
		delete(additionalProperties, "url")
		delete(additionalProperties, "status")
		delete(additionalProperties, "subscribed_events")
		delete(additionalProperties, "synchronous")
		delete(additionalProperties, "description")
		delete(additionalProperties, "livemode")
		delete(additionalProperties, "active")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookResponse struct {
	value *WebhookResponse
	isSet bool
}

func (v NullableWebhookResponse) Get() *WebhookResponse {
	return v.value
}

func (v *NullableWebhookResponse) Set(val *WebhookResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookResponse(val *WebhookResponse) *NullableWebhookResponse {
	return &NullableWebhookResponse{value: val, isSet: true}
}

func (v NullableWebhookResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


