/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
)

// checks if the ChannelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelResponse{}

// ChannelResponse Channel information.
type ChannelResponse struct {
	Segment *string `json:"segment,omitempty"`
	CheckoutRequestId *string `json:"checkout_request_id,omitempty"`
	CheckoutRequestType *string `json:"checkout_request_type,omitempty"`
	Id *string `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ChannelResponse ChannelResponse

// NewChannelResponse instantiates a new ChannelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelResponse() *ChannelResponse {
	this := ChannelResponse{}
	return &this
}

// NewChannelResponseWithDefaults instantiates a new ChannelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelResponseWithDefaults() *ChannelResponse {
	this := ChannelResponse{}
	return &this
}

// GetSegment returns the Segment field value if set, zero value otherwise.
func (o *ChannelResponse) GetSegment() string {
	if o == nil || IsNil(o.Segment) {
		var ret string
		return ret
	}
	return *o.Segment
}

// GetSegmentOk returns a tuple with the Segment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelResponse) GetSegmentOk() (*string, bool) {
	if o == nil || IsNil(o.Segment) {
		return nil, false
	}
	return o.Segment, true
}

// HasSegment returns a boolean if a field has been set.
func (o *ChannelResponse) HasSegment() bool {
	if o != nil && !IsNil(o.Segment) {
		return true
	}

	return false
}

// SetSegment gets a reference to the given string and assigns it to the Segment field.
func (o *ChannelResponse) SetSegment(v string) {
	o.Segment = &v
}

// GetCheckoutRequestId returns the CheckoutRequestId field value if set, zero value otherwise.
func (o *ChannelResponse) GetCheckoutRequestId() string {
	if o == nil || IsNil(o.CheckoutRequestId) {
		var ret string
		return ret
	}
	return *o.CheckoutRequestId
}

// GetCheckoutRequestIdOk returns a tuple with the CheckoutRequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelResponse) GetCheckoutRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.CheckoutRequestId) {
		return nil, false
	}
	return o.CheckoutRequestId, true
}

// HasCheckoutRequestId returns a boolean if a field has been set.
func (o *ChannelResponse) HasCheckoutRequestId() bool {
	if o != nil && !IsNil(o.CheckoutRequestId) {
		return true
	}

	return false
}

// SetCheckoutRequestId gets a reference to the given string and assigns it to the CheckoutRequestId field.
func (o *ChannelResponse) SetCheckoutRequestId(v string) {
	o.CheckoutRequestId = &v
}

// GetCheckoutRequestType returns the CheckoutRequestType field value if set, zero value otherwise.
func (o *ChannelResponse) GetCheckoutRequestType() string {
	if o == nil || IsNil(o.CheckoutRequestType) {
		var ret string
		return ret
	}
	return *o.CheckoutRequestType
}

// GetCheckoutRequestTypeOk returns a tuple with the CheckoutRequestType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelResponse) GetCheckoutRequestTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CheckoutRequestType) {
		return nil, false
	}
	return o.CheckoutRequestType, true
}

// HasCheckoutRequestType returns a boolean if a field has been set.
func (o *ChannelResponse) HasCheckoutRequestType() bool {
	if o != nil && !IsNil(o.CheckoutRequestType) {
		return true
	}

	return false
}

// SetCheckoutRequestType gets a reference to the given string and assigns it to the CheckoutRequestType field.
func (o *ChannelResponse) SetCheckoutRequestType(v string) {
	o.CheckoutRequestType = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ChannelResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ChannelResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ChannelResponse) SetId(v string) {
	o.Id = &v
}

func (o ChannelResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Segment) {
		toSerialize["segment"] = o.Segment
	}
	if !IsNil(o.CheckoutRequestId) {
		toSerialize["checkout_request_id"] = o.CheckoutRequestId
	}
	if !IsNil(o.CheckoutRequestType) {
		toSerialize["checkout_request_type"] = o.CheckoutRequestType
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ChannelResponse) UnmarshalJSON(data []byte) (err error) {
	varChannelResponse := _ChannelResponse{}

	err = json.Unmarshal(data, &varChannelResponse)

	if err != nil {
		return err
	}

	*o = ChannelResponse(varChannelResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "segment")
		delete(additionalProperties, "checkout_request_id")
		delete(additionalProperties, "checkout_request_type")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableChannelResponse struct {
	value *ChannelResponse
	isSet bool
}

func (v NullableChannelResponse) Get() *ChannelResponse {
	return v.value
}

func (v *NullableChannelResponse) Set(val *ChannelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelResponse(val *ChannelResponse) *NullableChannelResponse {
	return &NullableChannelResponse{value: val, isSet: true}
}

func (v NullableChannelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


