/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
	"fmt"
)

// checks if the OrderUpdateFiscalEntityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrderUpdateFiscalEntityRequest{}

// OrderUpdateFiscalEntityRequest Fiscal entity information associated with the order.
type OrderUpdateFiscalEntityRequest struct {
	Address FiscalEntityAddress `json:"address"`
	// Email of the fiscal entity
	Email *string `json:"email,omitempty"`
	// Name of the fiscal entity
	Name NullableString `json:"name,omitempty"`
	// Metadata associated with the fiscal entity
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Phone of the fiscal entity
	Phone *string `json:"phone,omitempty"`
	// Tax ID of the fiscal entity
	TaxId NullableString `json:"tax_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OrderUpdateFiscalEntityRequest OrderUpdateFiscalEntityRequest

// NewOrderUpdateFiscalEntityRequest instantiates a new OrderUpdateFiscalEntityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrderUpdateFiscalEntityRequest(address FiscalEntityAddress) *OrderUpdateFiscalEntityRequest {
	this := OrderUpdateFiscalEntityRequest{}
	this.Address = address
	return &this
}

// NewOrderUpdateFiscalEntityRequestWithDefaults instantiates a new OrderUpdateFiscalEntityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrderUpdateFiscalEntityRequestWithDefaults() *OrderUpdateFiscalEntityRequest {
	this := OrderUpdateFiscalEntityRequest{}
	return &this
}

// GetAddress returns the Address field value
func (o *OrderUpdateFiscalEntityRequest) GetAddress() FiscalEntityAddress {
	if o == nil {
		var ret FiscalEntityAddress
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *OrderUpdateFiscalEntityRequest) GetAddressOk() (*FiscalEntityAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *OrderUpdateFiscalEntityRequest) SetAddress(v FiscalEntityAddress) {
	o.Address = v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *OrderUpdateFiscalEntityRequest) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdateFiscalEntityRequest) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *OrderUpdateFiscalEntityRequest) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *OrderUpdateFiscalEntityRequest) SetEmail(v string) {
	o.Email = &v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderUpdateFiscalEntityRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderUpdateFiscalEntityRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *OrderUpdateFiscalEntityRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *OrderUpdateFiscalEntityRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *OrderUpdateFiscalEntityRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *OrderUpdateFiscalEntityRequest) UnsetName() {
	o.Name.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *OrderUpdateFiscalEntityRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdateFiscalEntityRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *OrderUpdateFiscalEntityRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *OrderUpdateFiscalEntityRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *OrderUpdateFiscalEntityRequest) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrderUpdateFiscalEntityRequest) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *OrderUpdateFiscalEntityRequest) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *OrderUpdateFiscalEntityRequest) SetPhone(v string) {
	o.Phone = &v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OrderUpdateFiscalEntityRequest) GetTaxId() string {
	if o == nil || IsNil(o.TaxId.Get()) {
		var ret string
		return ret
	}
	return *o.TaxId.Get()
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OrderUpdateFiscalEntityRequest) GetTaxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TaxId.Get(), o.TaxId.IsSet()
}

// HasTaxId returns a boolean if a field has been set.
func (o *OrderUpdateFiscalEntityRequest) HasTaxId() bool {
	if o != nil && o.TaxId.IsSet() {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given NullableString and assigns it to the TaxId field.
func (o *OrderUpdateFiscalEntityRequest) SetTaxId(v string) {
	o.TaxId.Set(&v)
}
// SetTaxIdNil sets the value for TaxId to be an explicit nil
func (o *OrderUpdateFiscalEntityRequest) SetTaxIdNil() {
	o.TaxId.Set(nil)
}

// UnsetTaxId ensures that no value is present for TaxId, not even an explicit nil
func (o *OrderUpdateFiscalEntityRequest) UnsetTaxId() {
	o.TaxId.Unset()
}

func (o OrderUpdateFiscalEntityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrderUpdateFiscalEntityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if o.TaxId.IsSet() {
		toSerialize["tax_id"] = o.TaxId.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OrderUpdateFiscalEntityRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrderUpdateFiscalEntityRequest := _OrderUpdateFiscalEntityRequest{}

	err = json.Unmarshal(data, &varOrderUpdateFiscalEntityRequest)

	if err != nil {
		return err
	}

	*o = OrderUpdateFiscalEntityRequest(varOrderUpdateFiscalEntityRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "address")
		delete(additionalProperties, "email")
		delete(additionalProperties, "name")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "phone")
		delete(additionalProperties, "tax_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOrderUpdateFiscalEntityRequest struct {
	value *OrderUpdateFiscalEntityRequest
	isSet bool
}

func (v NullableOrderUpdateFiscalEntityRequest) Get() *OrderUpdateFiscalEntityRequest {
	return v.value
}

func (v *NullableOrderUpdateFiscalEntityRequest) Set(val *OrderUpdateFiscalEntityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOrderUpdateFiscalEntityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOrderUpdateFiscalEntityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrderUpdateFiscalEntityRequest(val *OrderUpdateFiscalEntityRequest) *NullableOrderUpdateFiscalEntityRequest {
	return &NullableOrderUpdateFiscalEntityRequest{value: val, isSet: true}
}

func (v NullableOrderUpdateFiscalEntityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrderUpdateFiscalEntityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


