/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomerFiscalEntitiesResponse1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerFiscalEntitiesResponse1{}

// CustomerFiscalEntitiesResponse1 struct for CustomerFiscalEntitiesResponse1
type CustomerFiscalEntitiesResponse1 struct {
	// Indicates if there are more pages to be requested
	HasMore bool `json:"has_more"`
	// Object type, in this case is list
	Object string `json:"object"`
	// URL of the next page.
	NextPageUrl NullableString `json:"next_page_url,omitempty"`
	// Url of the previous page.
	PreviousPageUrl NullableString `json:"previous_page_url,omitempty"`
	Data []CustomerFiscalEntitiesResponse `json:"data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerFiscalEntitiesResponse1 CustomerFiscalEntitiesResponse1

// NewCustomerFiscalEntitiesResponse1 instantiates a new CustomerFiscalEntitiesResponse1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerFiscalEntitiesResponse1(hasMore bool, object string) *CustomerFiscalEntitiesResponse1 {
	this := CustomerFiscalEntitiesResponse1{}
	this.HasMore = hasMore
	this.Object = object
	return &this
}

// NewCustomerFiscalEntitiesResponse1WithDefaults instantiates a new CustomerFiscalEntitiesResponse1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerFiscalEntitiesResponse1WithDefaults() *CustomerFiscalEntitiesResponse1 {
	this := CustomerFiscalEntitiesResponse1{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *CustomerFiscalEntitiesResponse1) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *CustomerFiscalEntitiesResponse1) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *CustomerFiscalEntitiesResponse1) SetHasMore(v bool) {
	o.HasMore = v
}

// GetObject returns the Object field value
func (o *CustomerFiscalEntitiesResponse1) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *CustomerFiscalEntitiesResponse1) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *CustomerFiscalEntitiesResponse1) SetObject(v string) {
	o.Object = v
}

// GetNextPageUrl returns the NextPageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerFiscalEntitiesResponse1) GetNextPageUrl() string {
	if o == nil || IsNil(o.NextPageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.NextPageUrl.Get()
}

// GetNextPageUrlOk returns a tuple with the NextPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerFiscalEntitiesResponse1) GetNextPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextPageUrl.Get(), o.NextPageUrl.IsSet()
}

// HasNextPageUrl returns a boolean if a field has been set.
func (o *CustomerFiscalEntitiesResponse1) HasNextPageUrl() bool {
	if o != nil && o.NextPageUrl.IsSet() {
		return true
	}

	return false
}

// SetNextPageUrl gets a reference to the given NullableString and assigns it to the NextPageUrl field.
func (o *CustomerFiscalEntitiesResponse1) SetNextPageUrl(v string) {
	o.NextPageUrl.Set(&v)
}
// SetNextPageUrlNil sets the value for NextPageUrl to be an explicit nil
func (o *CustomerFiscalEntitiesResponse1) SetNextPageUrlNil() {
	o.NextPageUrl.Set(nil)
}

// UnsetNextPageUrl ensures that no value is present for NextPageUrl, not even an explicit nil
func (o *CustomerFiscalEntitiesResponse1) UnsetNextPageUrl() {
	o.NextPageUrl.Unset()
}

// GetPreviousPageUrl returns the PreviousPageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerFiscalEntitiesResponse1) GetPreviousPageUrl() string {
	if o == nil || IsNil(o.PreviousPageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.PreviousPageUrl.Get()
}

// GetPreviousPageUrlOk returns a tuple with the PreviousPageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerFiscalEntitiesResponse1) GetPreviousPageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviousPageUrl.Get(), o.PreviousPageUrl.IsSet()
}

// HasPreviousPageUrl returns a boolean if a field has been set.
func (o *CustomerFiscalEntitiesResponse1) HasPreviousPageUrl() bool {
	if o != nil && o.PreviousPageUrl.IsSet() {
		return true
	}

	return false
}

// SetPreviousPageUrl gets a reference to the given NullableString and assigns it to the PreviousPageUrl field.
func (o *CustomerFiscalEntitiesResponse1) SetPreviousPageUrl(v string) {
	o.PreviousPageUrl.Set(&v)
}
// SetPreviousPageUrlNil sets the value for PreviousPageUrl to be an explicit nil
func (o *CustomerFiscalEntitiesResponse1) SetPreviousPageUrlNil() {
	o.PreviousPageUrl.Set(nil)
}

// UnsetPreviousPageUrl ensures that no value is present for PreviousPageUrl, not even an explicit nil
func (o *CustomerFiscalEntitiesResponse1) UnsetPreviousPageUrl() {
	o.PreviousPageUrl.Unset()
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CustomerFiscalEntitiesResponse1) GetData() []CustomerFiscalEntitiesResponse {
	if o == nil || IsNil(o.Data) {
		var ret []CustomerFiscalEntitiesResponse
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerFiscalEntitiesResponse1) GetDataOk() ([]CustomerFiscalEntitiesResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CustomerFiscalEntitiesResponse1) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []CustomerFiscalEntitiesResponse and assigns it to the Data field.
func (o *CustomerFiscalEntitiesResponse1) SetData(v []CustomerFiscalEntitiesResponse) {
	o.Data = v
}

func (o CustomerFiscalEntitiesResponse1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerFiscalEntitiesResponse1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["has_more"] = o.HasMore
	toSerialize["object"] = o.Object
	if o.NextPageUrl.IsSet() {
		toSerialize["next_page_url"] = o.NextPageUrl.Get()
	}
	if o.PreviousPageUrl.IsSet() {
		toSerialize["previous_page_url"] = o.PreviousPageUrl.Get()
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerFiscalEntitiesResponse1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"has_more",
		"object",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerFiscalEntitiesResponse1 := _CustomerFiscalEntitiesResponse1{}

	err = json.Unmarshal(data, &varCustomerFiscalEntitiesResponse1)

	if err != nil {
		return err
	}

	*o = CustomerFiscalEntitiesResponse1(varCustomerFiscalEntitiesResponse1)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "has_more")
		delete(additionalProperties, "object")
		delete(additionalProperties, "next_page_url")
		delete(additionalProperties, "previous_page_url")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerFiscalEntitiesResponse1 struct {
	value *CustomerFiscalEntitiesResponse1
	isSet bool
}

func (v NullableCustomerFiscalEntitiesResponse1) Get() *CustomerFiscalEntitiesResponse1 {
	return v.value
}

func (v *NullableCustomerFiscalEntitiesResponse1) Set(val *CustomerFiscalEntitiesResponse1) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerFiscalEntitiesResponse1) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerFiscalEntitiesResponse1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerFiscalEntitiesResponse1(val *CustomerFiscalEntitiesResponse1) *NullableCustomerFiscalEntitiesResponse1 {
	return &NullableCustomerFiscalEntitiesResponse1{value: val, isSet: true}
}

func (v NullableCustomerFiscalEntitiesResponse1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerFiscalEntitiesResponse1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


