/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
)

// checks if the WebhookUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookUpdateRequest{}

// WebhookUpdateRequest Parameters used to update a webhook. All fields are optional; send only the fields you want to change.
type WebhookUpdateRequest struct {
	// Webhook endpoint URL. Local URLs are not allowed.
	Url *string `json:"url,omitempty"`
	// List of event types the webhook is subscribed to.
	SubscribedEvents []string `json:"subscribed_events,omitempty"`
	// Alias for subscribed_events.
	// Deprecated
	Events []string `json:"events,omitempty"`
	// Indicates whether the webhook uses synchronous delivery behavior.
	Synchronous *bool `json:"synchronous,omitempty"`
	// Activates or deactivates the webhook.
	Active *bool `json:"active,omitempty"`
	// Optional description of the webhook.
	Description NullableString `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WebhookUpdateRequest WebhookUpdateRequest

// NewWebhookUpdateRequest instantiates a new WebhookUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookUpdateRequest() *WebhookUpdateRequest {
	this := WebhookUpdateRequest{}
	var synchronous bool = false
	this.Synchronous = &synchronous
	return &this
}

// NewWebhookUpdateRequestWithDefaults instantiates a new WebhookUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookUpdateRequestWithDefaults() *WebhookUpdateRequest {
	this := WebhookUpdateRequest{}
	var synchronous bool = false
	this.Synchronous = &synchronous
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *WebhookUpdateRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdateRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *WebhookUpdateRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *WebhookUpdateRequest) SetUrl(v string) {
	o.Url = &v
}

// GetSubscribedEvents returns the SubscribedEvents field value if set, zero value otherwise.
func (o *WebhookUpdateRequest) GetSubscribedEvents() []string {
	if o == nil || IsNil(o.SubscribedEvents) {
		var ret []string
		return ret
	}
	return o.SubscribedEvents
}

// GetSubscribedEventsOk returns a tuple with the SubscribedEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdateRequest) GetSubscribedEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.SubscribedEvents) {
		return nil, false
	}
	return o.SubscribedEvents, true
}

// HasSubscribedEvents returns a boolean if a field has been set.
func (o *WebhookUpdateRequest) HasSubscribedEvents() bool {
	if o != nil && !IsNil(o.SubscribedEvents) {
		return true
	}

	return false
}

// SetSubscribedEvents gets a reference to the given []string and assigns it to the SubscribedEvents field.
func (o *WebhookUpdateRequest) SetSubscribedEvents(v []string) {
	o.SubscribedEvents = v
}

// GetEvents returns the Events field value if set, zero value otherwise.
// Deprecated
func (o *WebhookUpdateRequest) GetEvents() []string {
	if o == nil || IsNil(o.Events) {
		var ret []string
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *WebhookUpdateRequest) GetEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *WebhookUpdateRequest) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []string and assigns it to the Events field.
// Deprecated
func (o *WebhookUpdateRequest) SetEvents(v []string) {
	o.Events = v
}

// GetSynchronous returns the Synchronous field value if set, zero value otherwise.
func (o *WebhookUpdateRequest) GetSynchronous() bool {
	if o == nil || IsNil(o.Synchronous) {
		var ret bool
		return ret
	}
	return *o.Synchronous
}

// GetSynchronousOk returns a tuple with the Synchronous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdateRequest) GetSynchronousOk() (*bool, bool) {
	if o == nil || IsNil(o.Synchronous) {
		return nil, false
	}
	return o.Synchronous, true
}

// HasSynchronous returns a boolean if a field has been set.
func (o *WebhookUpdateRequest) HasSynchronous() bool {
	if o != nil && !IsNil(o.Synchronous) {
		return true
	}

	return false
}

// SetSynchronous gets a reference to the given bool and assigns it to the Synchronous field.
func (o *WebhookUpdateRequest) SetSynchronous(v bool) {
	o.Synchronous = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *WebhookUpdateRequest) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookUpdateRequest) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *WebhookUpdateRequest) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *WebhookUpdateRequest) SetActive(v bool) {
	o.Active = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookUpdateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *WebhookUpdateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *WebhookUpdateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *WebhookUpdateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *WebhookUpdateRequest) UnsetDescription() {
	o.Description.Unset()
}

func (o WebhookUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.SubscribedEvents) {
		toSerialize["subscribed_events"] = o.SubscribedEvents
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	if !IsNil(o.Synchronous) {
		toSerialize["synchronous"] = o.Synchronous
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	varWebhookUpdateRequest := _WebhookUpdateRequest{}

	err = json.Unmarshal(data, &varWebhookUpdateRequest)

	if err != nil {
		return err
	}

	*o = WebhookUpdateRequest(varWebhookUpdateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "subscribed_events")
		delete(additionalProperties, "events")
		delete(additionalProperties, "synchronous")
		delete(additionalProperties, "active")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookUpdateRequest struct {
	value *WebhookUpdateRequest
	isSet bool
}

func (v NullableWebhookUpdateRequest) Get() *WebhookUpdateRequest {
	return v.value
}

func (v *NullableWebhookUpdateRequest) Set(val *WebhookUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookUpdateRequest(val *WebhookUpdateRequest) *NullableWebhookUpdateRequest {
	return &NullableWebhookUpdateRequest{value: val, isSet: true}
}

func (v NullableWebhookUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


