/*
Femsa API

Femsa sdk

API version: 2.1.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerInfo{}

// CustomerInfo struct for CustomerInfo
type CustomerInfo struct {
	CustomerId *string `json:"customer_id,omitempty"`
	Name string `json:"name"`
	Email string `json:"email"`
	Phone *string `json:"phone,omitempty"`
	Corporate *bool `json:"corporate,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerInfo CustomerInfo

// NewCustomerInfo instantiates a new CustomerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerInfo(name string, email string) *CustomerInfo {
	this := CustomerInfo{}
	this.Name = name
	this.Email = email
	return &this
}

// NewCustomerInfoWithDefaults instantiates a new CustomerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerInfoWithDefaults() *CustomerInfo {
	this := CustomerInfo{}
	return &this
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *CustomerInfo) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerInfo) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CustomerInfo) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *CustomerInfo) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetName returns the Name field value
func (o *CustomerInfo) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CustomerInfo) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CustomerInfo) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *CustomerInfo) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CustomerInfo) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CustomerInfo) SetEmail(v string) {
	o.Email = v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *CustomerInfo) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerInfo) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *CustomerInfo) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *CustomerInfo) SetPhone(v string) {
	o.Phone = &v
}

// GetCorporate returns the Corporate field value if set, zero value otherwise.
func (o *CustomerInfo) GetCorporate() bool {
	if o == nil || IsNil(o.Corporate) {
		var ret bool
		return ret
	}
	return *o.Corporate
}

// GetCorporateOk returns a tuple with the Corporate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerInfo) GetCorporateOk() (*bool, bool) {
	if o == nil || IsNil(o.Corporate) {
		return nil, false
	}
	return o.Corporate, true
}

// HasCorporate returns a boolean if a field has been set.
func (o *CustomerInfo) HasCorporate() bool {
	if o != nil && !IsNil(o.Corporate) {
		return true
	}

	return false
}

// SetCorporate gets a reference to the given bool and assigns it to the Corporate field.
func (o *CustomerInfo) SetCorporate(v bool) {
	o.Corporate = &v
}

func (o CustomerInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerId) {
		toSerialize["customer_id"] = o.CustomerId
	}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Corporate) {
		toSerialize["corporate"] = o.Corporate
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerInfo := _CustomerInfo{}

	err = json.Unmarshal(data, &varCustomerInfo)

	if err != nil {
		return err
	}

	*o = CustomerInfo(varCustomerInfo)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "customer_id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "email")
		delete(additionalProperties, "phone")
		delete(additionalProperties, "corporate")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerInfo struct {
	value *CustomerInfo
	isSet bool
}

func (v NullableCustomerInfo) Get() *CustomerInfo {
	return v.value
}

func (v *NullableCustomerInfo) Set(val *CustomerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerInfo(val *CustomerInfo) *NullableCustomerInfo {
	return &NullableCustomerInfo{value: val, isSet: true}
}

func (v NullableCustomerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


