/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
	"fmt"
)

// checks if the CustomerResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerResponse{}

// CustomerResponse customer response
type CustomerResponse struct {
	// Customer's ID
	Id string `json:"id"`
	Object string `json:"object"`
	// Creation date of the object (Unix timestamp)
	CreatedAt int64 `json:"created_at"`
	// true if the object exists in live mode or false if the object exists in test mode
	Livemode bool `json:"livemode"`
	// Customer's name
	Name NullableString `json:"name,omitempty"`
	Email NullableString `json:"email,omitempty"`
	// Customer's phone number
	Phone NullableString `json:"phone,omitempty"`
	// true if the customer is a company
	Corporate *bool `json:"corporate,omitempty"`
	// Custom reference
	CustomReference NullableString `json:"custom_reference,omitempty"`
	// Referrer information (if available)
	Referrer NullableString `json:"referrer,omitempty"`
	// Vertical-specific information (shape depends on integration)
	VerticalInfo map[string]interface{} `json:"vertical_info,omitempty"`
	DefaultFiscalEntityId NullableString `json:"default_fiscal_entity_id,omitempty"`
	DefaultShippingContactId NullableString `json:"default_shipping_contact_id,omitempty"`
	// Customer metadata (maps to contextual_data in backend)
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	PaymentSources *CustomerPaymentMethodsResponse `json:"payment_sources,omitempty"`
	FiscalEntities *CustomerFiscalEntitiesResponse `json:"fiscal_entities,omitempty"`
	ShippingContacts *CustomerResponseShippingContacts `json:"shipping_contacts,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomerResponse CustomerResponse

// NewCustomerResponse instantiates a new CustomerResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerResponse(id string, object string, createdAt int64, livemode bool) *CustomerResponse {
	this := CustomerResponse{}
	this.Id = id
	this.Object = object
	this.CreatedAt = createdAt
	this.Livemode = livemode
	return &this
}

// NewCustomerResponseWithDefaults instantiates a new CustomerResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerResponseWithDefaults() *CustomerResponse {
	this := CustomerResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CustomerResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomerResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomerResponse) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value
func (o *CustomerResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *CustomerResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *CustomerResponse) SetObject(v string) {
	o.Object = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CustomerResponse) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CustomerResponse) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CustomerResponse) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetLivemode returns the Livemode field value
func (o *CustomerResponse) GetLivemode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value
// and a boolean to check if the value has been set.
func (o *CustomerResponse) GetLivemodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livemode, true
}

// SetLivemode sets field value
func (o *CustomerResponse) SetLivemode(v bool) {
	o.Livemode = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerResponse) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CustomerResponse) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *CustomerResponse) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *CustomerResponse) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CustomerResponse) UnsetName() {
	o.Name.Unset()
}

// GetEmail returns the Email field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerResponse) GetEmail() string {
	if o == nil || IsNil(o.Email.Get()) {
		var ret string
		return ret
	}
	return *o.Email.Get()
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Email.Get(), o.Email.IsSet()
}

// HasEmail returns a boolean if a field has been set.
func (o *CustomerResponse) HasEmail() bool {
	if o != nil && o.Email.IsSet() {
		return true
	}

	return false
}

// SetEmail gets a reference to the given NullableString and assigns it to the Email field.
func (o *CustomerResponse) SetEmail(v string) {
	o.Email.Set(&v)
}
// SetEmailNil sets the value for Email to be an explicit nil
func (o *CustomerResponse) SetEmailNil() {
	o.Email.Set(nil)
}

// UnsetEmail ensures that no value is present for Email, not even an explicit nil
func (o *CustomerResponse) UnsetEmail() {
	o.Email.Unset()
}

// GetPhone returns the Phone field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerResponse) GetPhone() string {
	if o == nil || IsNil(o.Phone.Get()) {
		var ret string
		return ret
	}
	return *o.Phone.Get()
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerResponse) GetPhoneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phone.Get(), o.Phone.IsSet()
}

// HasPhone returns a boolean if a field has been set.
func (o *CustomerResponse) HasPhone() bool {
	if o != nil && o.Phone.IsSet() {
		return true
	}

	return false
}

// SetPhone gets a reference to the given NullableString and assigns it to the Phone field.
func (o *CustomerResponse) SetPhone(v string) {
	o.Phone.Set(&v)
}
// SetPhoneNil sets the value for Phone to be an explicit nil
func (o *CustomerResponse) SetPhoneNil() {
	o.Phone.Set(nil)
}

// UnsetPhone ensures that no value is present for Phone, not even an explicit nil
func (o *CustomerResponse) UnsetPhone() {
	o.Phone.Unset()
}

// GetCorporate returns the Corporate field value if set, zero value otherwise.
func (o *CustomerResponse) GetCorporate() bool {
	if o == nil || IsNil(o.Corporate) {
		var ret bool
		return ret
	}
	return *o.Corporate
}

// GetCorporateOk returns a tuple with the Corporate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerResponse) GetCorporateOk() (*bool, bool) {
	if o == nil || IsNil(o.Corporate) {
		return nil, false
	}
	return o.Corporate, true
}

// HasCorporate returns a boolean if a field has been set.
func (o *CustomerResponse) HasCorporate() bool {
	if o != nil && !IsNil(o.Corporate) {
		return true
	}

	return false
}

// SetCorporate gets a reference to the given bool and assigns it to the Corporate field.
func (o *CustomerResponse) SetCorporate(v bool) {
	o.Corporate = &v
}

// GetCustomReference returns the CustomReference field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerResponse) GetCustomReference() string {
	if o == nil || IsNil(o.CustomReference.Get()) {
		var ret string
		return ret
	}
	return *o.CustomReference.Get()
}

// GetCustomReferenceOk returns a tuple with the CustomReference field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerResponse) GetCustomReferenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CustomReference.Get(), o.CustomReference.IsSet()
}

// HasCustomReference returns a boolean if a field has been set.
func (o *CustomerResponse) HasCustomReference() bool {
	if o != nil && o.CustomReference.IsSet() {
		return true
	}

	return false
}

// SetCustomReference gets a reference to the given NullableString and assigns it to the CustomReference field.
func (o *CustomerResponse) SetCustomReference(v string) {
	o.CustomReference.Set(&v)
}
// SetCustomReferenceNil sets the value for CustomReference to be an explicit nil
func (o *CustomerResponse) SetCustomReferenceNil() {
	o.CustomReference.Set(nil)
}

// UnsetCustomReference ensures that no value is present for CustomReference, not even an explicit nil
func (o *CustomerResponse) UnsetCustomReference() {
	o.CustomReference.Unset()
}

// GetReferrer returns the Referrer field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerResponse) GetReferrer() string {
	if o == nil || IsNil(o.Referrer.Get()) {
		var ret string
		return ret
	}
	return *o.Referrer.Get()
}

// GetReferrerOk returns a tuple with the Referrer field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerResponse) GetReferrerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Referrer.Get(), o.Referrer.IsSet()
}

// HasReferrer returns a boolean if a field has been set.
func (o *CustomerResponse) HasReferrer() bool {
	if o != nil && o.Referrer.IsSet() {
		return true
	}

	return false
}

// SetReferrer gets a reference to the given NullableString and assigns it to the Referrer field.
func (o *CustomerResponse) SetReferrer(v string) {
	o.Referrer.Set(&v)
}
// SetReferrerNil sets the value for Referrer to be an explicit nil
func (o *CustomerResponse) SetReferrerNil() {
	o.Referrer.Set(nil)
}

// UnsetReferrer ensures that no value is present for Referrer, not even an explicit nil
func (o *CustomerResponse) UnsetReferrer() {
	o.Referrer.Unset()
}

// GetVerticalInfo returns the VerticalInfo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerResponse) GetVerticalInfo() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.VerticalInfo
}

// GetVerticalInfoOk returns a tuple with the VerticalInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerResponse) GetVerticalInfoOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.VerticalInfo) {
		return map[string]interface{}{}, false
	}
	return o.VerticalInfo, true
}

// HasVerticalInfo returns a boolean if a field has been set.
func (o *CustomerResponse) HasVerticalInfo() bool {
	if o != nil && !IsNil(o.VerticalInfo) {
		return true
	}

	return false
}

// SetVerticalInfo gets a reference to the given map[string]interface{} and assigns it to the VerticalInfo field.
func (o *CustomerResponse) SetVerticalInfo(v map[string]interface{}) {
	o.VerticalInfo = v
}

// GetDefaultFiscalEntityId returns the DefaultFiscalEntityId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerResponse) GetDefaultFiscalEntityId() string {
	if o == nil || IsNil(o.DefaultFiscalEntityId.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultFiscalEntityId.Get()
}

// GetDefaultFiscalEntityIdOk returns a tuple with the DefaultFiscalEntityId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerResponse) GetDefaultFiscalEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultFiscalEntityId.Get(), o.DefaultFiscalEntityId.IsSet()
}

// HasDefaultFiscalEntityId returns a boolean if a field has been set.
func (o *CustomerResponse) HasDefaultFiscalEntityId() bool {
	if o != nil && o.DefaultFiscalEntityId.IsSet() {
		return true
	}

	return false
}

// SetDefaultFiscalEntityId gets a reference to the given NullableString and assigns it to the DefaultFiscalEntityId field.
func (o *CustomerResponse) SetDefaultFiscalEntityId(v string) {
	o.DefaultFiscalEntityId.Set(&v)
}
// SetDefaultFiscalEntityIdNil sets the value for DefaultFiscalEntityId to be an explicit nil
func (o *CustomerResponse) SetDefaultFiscalEntityIdNil() {
	o.DefaultFiscalEntityId.Set(nil)
}

// UnsetDefaultFiscalEntityId ensures that no value is present for DefaultFiscalEntityId, not even an explicit nil
func (o *CustomerResponse) UnsetDefaultFiscalEntityId() {
	o.DefaultFiscalEntityId.Unset()
}

// GetDefaultShippingContactId returns the DefaultShippingContactId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerResponse) GetDefaultShippingContactId() string {
	if o == nil || IsNil(o.DefaultShippingContactId.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultShippingContactId.Get()
}

// GetDefaultShippingContactIdOk returns a tuple with the DefaultShippingContactId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerResponse) GetDefaultShippingContactIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultShippingContactId.Get(), o.DefaultShippingContactId.IsSet()
}

// HasDefaultShippingContactId returns a boolean if a field has been set.
func (o *CustomerResponse) HasDefaultShippingContactId() bool {
	if o != nil && o.DefaultShippingContactId.IsSet() {
		return true
	}

	return false
}

// SetDefaultShippingContactId gets a reference to the given NullableString and assigns it to the DefaultShippingContactId field.
func (o *CustomerResponse) SetDefaultShippingContactId(v string) {
	o.DefaultShippingContactId.Set(&v)
}
// SetDefaultShippingContactIdNil sets the value for DefaultShippingContactId to be an explicit nil
func (o *CustomerResponse) SetDefaultShippingContactIdNil() {
	o.DefaultShippingContactId.Set(nil)
}

// UnsetDefaultShippingContactId ensures that no value is present for DefaultShippingContactId, not even an explicit nil
func (o *CustomerResponse) UnsetDefaultShippingContactId() {
	o.DefaultShippingContactId.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomerResponse) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerResponse) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CustomerResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CustomerResponse) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetPaymentSources returns the PaymentSources field value if set, zero value otherwise.
func (o *CustomerResponse) GetPaymentSources() CustomerPaymentMethodsResponse {
	if o == nil || IsNil(o.PaymentSources) {
		var ret CustomerPaymentMethodsResponse
		return ret
	}
	return *o.PaymentSources
}

// GetPaymentSourcesOk returns a tuple with the PaymentSources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerResponse) GetPaymentSourcesOk() (*CustomerPaymentMethodsResponse, bool) {
	if o == nil || IsNil(o.PaymentSources) {
		return nil, false
	}
	return o.PaymentSources, true
}

// HasPaymentSources returns a boolean if a field has been set.
func (o *CustomerResponse) HasPaymentSources() bool {
	if o != nil && !IsNil(o.PaymentSources) {
		return true
	}

	return false
}

// SetPaymentSources gets a reference to the given CustomerPaymentMethodsResponse and assigns it to the PaymentSources field.
func (o *CustomerResponse) SetPaymentSources(v CustomerPaymentMethodsResponse) {
	o.PaymentSources = &v
}

// GetFiscalEntities returns the FiscalEntities field value if set, zero value otherwise.
func (o *CustomerResponse) GetFiscalEntities() CustomerFiscalEntitiesResponse {
	if o == nil || IsNil(o.FiscalEntities) {
		var ret CustomerFiscalEntitiesResponse
		return ret
	}
	return *o.FiscalEntities
}

// GetFiscalEntitiesOk returns a tuple with the FiscalEntities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerResponse) GetFiscalEntitiesOk() (*CustomerFiscalEntitiesResponse, bool) {
	if o == nil || IsNil(o.FiscalEntities) {
		return nil, false
	}
	return o.FiscalEntities, true
}

// HasFiscalEntities returns a boolean if a field has been set.
func (o *CustomerResponse) HasFiscalEntities() bool {
	if o != nil && !IsNil(o.FiscalEntities) {
		return true
	}

	return false
}

// SetFiscalEntities gets a reference to the given CustomerFiscalEntitiesResponse and assigns it to the FiscalEntities field.
func (o *CustomerResponse) SetFiscalEntities(v CustomerFiscalEntitiesResponse) {
	o.FiscalEntities = &v
}

// GetShippingContacts returns the ShippingContacts field value if set, zero value otherwise.
func (o *CustomerResponse) GetShippingContacts() CustomerResponseShippingContacts {
	if o == nil || IsNil(o.ShippingContacts) {
		var ret CustomerResponseShippingContacts
		return ret
	}
	return *o.ShippingContacts
}

// GetShippingContactsOk returns a tuple with the ShippingContacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerResponse) GetShippingContactsOk() (*CustomerResponseShippingContacts, bool) {
	if o == nil || IsNil(o.ShippingContacts) {
		return nil, false
	}
	return o.ShippingContacts, true
}

// HasShippingContacts returns a boolean if a field has been set.
func (o *CustomerResponse) HasShippingContacts() bool {
	if o != nil && !IsNil(o.ShippingContacts) {
		return true
	}

	return false
}

// SetShippingContacts gets a reference to the given CustomerResponseShippingContacts and assigns it to the ShippingContacts field.
func (o *CustomerResponse) SetShippingContacts(v CustomerResponseShippingContacts) {
	o.ShippingContacts = &v
}

func (o CustomerResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["object"] = o.Object
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["livemode"] = o.Livemode
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Email.IsSet() {
		toSerialize["email"] = o.Email.Get()
	}
	if o.Phone.IsSet() {
		toSerialize["phone"] = o.Phone.Get()
	}
	if !IsNil(o.Corporate) {
		toSerialize["corporate"] = o.Corporate
	}
	if o.CustomReference.IsSet() {
		toSerialize["custom_reference"] = o.CustomReference.Get()
	}
	if o.Referrer.IsSet() {
		toSerialize["referrer"] = o.Referrer.Get()
	}
	if o.VerticalInfo != nil {
		toSerialize["vertical_info"] = o.VerticalInfo
	}
	if o.DefaultFiscalEntityId.IsSet() {
		toSerialize["default_fiscal_entity_id"] = o.DefaultFiscalEntityId.Get()
	}
	if o.DefaultShippingContactId.IsSet() {
		toSerialize["default_shipping_contact_id"] = o.DefaultShippingContactId.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.PaymentSources) {
		toSerialize["payment_sources"] = o.PaymentSources
	}
	if !IsNil(o.FiscalEntities) {
		toSerialize["fiscal_entities"] = o.FiscalEntities
	}
	if !IsNil(o.ShippingContacts) {
		toSerialize["shipping_contacts"] = o.ShippingContacts
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomerResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"object",
		"created_at",
		"livemode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerResponse := _CustomerResponse{}

	err = json.Unmarshal(data, &varCustomerResponse)

	if err != nil {
		return err
	}

	*o = CustomerResponse(varCustomerResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "livemode")
		delete(additionalProperties, "name")
		delete(additionalProperties, "email")
		delete(additionalProperties, "phone")
		delete(additionalProperties, "corporate")
		delete(additionalProperties, "custom_reference")
		delete(additionalProperties, "referrer")
		delete(additionalProperties, "vertical_info")
		delete(additionalProperties, "default_fiscal_entity_id")
		delete(additionalProperties, "default_shipping_contact_id")
		delete(additionalProperties, "metadata")
		delete(additionalProperties, "payment_sources")
		delete(additionalProperties, "fiscal_entities")
		delete(additionalProperties, "shipping_contacts")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomerResponse struct {
	value *CustomerResponse
	isSet bool
}

func (v NullableCustomerResponse) Get() *CustomerResponse {
	return v.value
}

func (v *NullableCustomerResponse) Set(val *CustomerResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerResponse(val *CustomerResponse) *NullableCustomerResponse {
	return &NullableCustomerResponse{value: val, isSet: true}
}

func (v NullableCustomerResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


