/*
Femsa API

Femsa sdk

API version: 2.2.0
Contact: engineering@femsa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package digitalfemsa

import (
	"encoding/json"
	"fmt"
)

// checks if the WebhookKeyCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookKeyCreateResponse{}

// WebhookKeyCreateResponse webhook keys model
type WebhookKeyCreateResponse struct {
	// Unique identifier of the webhook key
	Id string `json:"id"`
	// Object name, value is webhook_key
	Object string `json:"object"`
	// Indicates if the webhook key is active
	Active bool `json:"active"`
	// Indicates if the webhook key is in live mode
	Livemode bool `json:"livemode"`
	// Unix timestamp in seconds with the creation date of the webhook key
	CreatedAt int64 `json:"created_at"`
	// Unix timestamp in seconds when the webhook key was deactivated (if applicable).
	DeactivatedAt NullableInt64 `json:"deactivated_at,omitempty"`
	// Present only when the webhook key is deleted.
	Deleted NullableBool `json:"deleted,omitempty"`
	// Public key to be used in the webhook.
	PublicKey NullableString `json:"public_key,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WebhookKeyCreateResponse WebhookKeyCreateResponse

// NewWebhookKeyCreateResponse instantiates a new WebhookKeyCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookKeyCreateResponse(id string, object string, active bool, livemode bool, createdAt int64) *WebhookKeyCreateResponse {
	this := WebhookKeyCreateResponse{}
	this.Id = id
	this.Object = object
	this.Active = active
	this.Livemode = livemode
	this.CreatedAt = createdAt
	return &this
}

// NewWebhookKeyCreateResponseWithDefaults instantiates a new WebhookKeyCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookKeyCreateResponseWithDefaults() *WebhookKeyCreateResponse {
	this := WebhookKeyCreateResponse{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookKeyCreateResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookKeyCreateResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookKeyCreateResponse) SetId(v string) {
	o.Id = v
}

// GetObject returns the Object field value
func (o *WebhookKeyCreateResponse) GetObject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *WebhookKeyCreateResponse) GetObjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *WebhookKeyCreateResponse) SetObject(v string) {
	o.Object = v
}

// GetActive returns the Active field value
func (o *WebhookKeyCreateResponse) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *WebhookKeyCreateResponse) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *WebhookKeyCreateResponse) SetActive(v bool) {
	o.Active = v
}

// GetLivemode returns the Livemode field value
func (o *WebhookKeyCreateResponse) GetLivemode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Livemode
}

// GetLivemodeOk returns a tuple with the Livemode field value
// and a boolean to check if the value has been set.
func (o *WebhookKeyCreateResponse) GetLivemodeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Livemode, true
}

// SetLivemode sets field value
func (o *WebhookKeyCreateResponse) SetLivemode(v bool) {
	o.Livemode = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WebhookKeyCreateResponse) GetCreatedAt() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookKeyCreateResponse) GetCreatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WebhookKeyCreateResponse) SetCreatedAt(v int64) {
	o.CreatedAt = v
}

// GetDeactivatedAt returns the DeactivatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookKeyCreateResponse) GetDeactivatedAt() int64 {
	if o == nil || IsNil(o.DeactivatedAt.Get()) {
		var ret int64
		return ret
	}
	return *o.DeactivatedAt.Get()
}

// GetDeactivatedAtOk returns a tuple with the DeactivatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookKeyCreateResponse) GetDeactivatedAtOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeactivatedAt.Get(), o.DeactivatedAt.IsSet()
}

// HasDeactivatedAt returns a boolean if a field has been set.
func (o *WebhookKeyCreateResponse) HasDeactivatedAt() bool {
	if o != nil && o.DeactivatedAt.IsSet() {
		return true
	}

	return false
}

// SetDeactivatedAt gets a reference to the given NullableInt64 and assigns it to the DeactivatedAt field.
func (o *WebhookKeyCreateResponse) SetDeactivatedAt(v int64) {
	o.DeactivatedAt.Set(&v)
}
// SetDeactivatedAtNil sets the value for DeactivatedAt to be an explicit nil
func (o *WebhookKeyCreateResponse) SetDeactivatedAtNil() {
	o.DeactivatedAt.Set(nil)
}

// UnsetDeactivatedAt ensures that no value is present for DeactivatedAt, not even an explicit nil
func (o *WebhookKeyCreateResponse) UnsetDeactivatedAt() {
	o.DeactivatedAt.Unset()
}

// GetDeleted returns the Deleted field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookKeyCreateResponse) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted.Get()) {
		var ret bool
		return ret
	}
	return *o.Deleted.Get()
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookKeyCreateResponse) GetDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deleted.Get(), o.Deleted.IsSet()
}

// HasDeleted returns a boolean if a field has been set.
func (o *WebhookKeyCreateResponse) HasDeleted() bool {
	if o != nil && o.Deleted.IsSet() {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given NullableBool and assigns it to the Deleted field.
func (o *WebhookKeyCreateResponse) SetDeleted(v bool) {
	o.Deleted.Set(&v)
}
// SetDeletedNil sets the value for Deleted to be an explicit nil
func (o *WebhookKeyCreateResponse) SetDeletedNil() {
	o.Deleted.Set(nil)
}

// UnsetDeleted ensures that no value is present for Deleted, not even an explicit nil
func (o *WebhookKeyCreateResponse) UnsetDeleted() {
	o.Deleted.Unset()
}

// GetPublicKey returns the PublicKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WebhookKeyCreateResponse) GetPublicKey() string {
	if o == nil || IsNil(o.PublicKey.Get()) {
		var ret string
		return ret
	}
	return *o.PublicKey.Get()
}

// GetPublicKeyOk returns a tuple with the PublicKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WebhookKeyCreateResponse) GetPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PublicKey.Get(), o.PublicKey.IsSet()
}

// HasPublicKey returns a boolean if a field has been set.
func (o *WebhookKeyCreateResponse) HasPublicKey() bool {
	if o != nil && o.PublicKey.IsSet() {
		return true
	}

	return false
}

// SetPublicKey gets a reference to the given NullableString and assigns it to the PublicKey field.
func (o *WebhookKeyCreateResponse) SetPublicKey(v string) {
	o.PublicKey.Set(&v)
}
// SetPublicKeyNil sets the value for PublicKey to be an explicit nil
func (o *WebhookKeyCreateResponse) SetPublicKeyNil() {
	o.PublicKey.Set(nil)
}

// UnsetPublicKey ensures that no value is present for PublicKey, not even an explicit nil
func (o *WebhookKeyCreateResponse) UnsetPublicKey() {
	o.PublicKey.Unset()
}

func (o WebhookKeyCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookKeyCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["object"] = o.Object
	toSerialize["active"] = o.Active
	toSerialize["livemode"] = o.Livemode
	toSerialize["created_at"] = o.CreatedAt
	if o.DeactivatedAt.IsSet() {
		toSerialize["deactivated_at"] = o.DeactivatedAt.Get()
	}
	if o.Deleted.IsSet() {
		toSerialize["deleted"] = o.Deleted.Get()
	}
	if o.PublicKey.IsSet() {
		toSerialize["public_key"] = o.PublicKey.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WebhookKeyCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"object",
		"active",
		"livemode",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookKeyCreateResponse := _WebhookKeyCreateResponse{}

	err = json.Unmarshal(data, &varWebhookKeyCreateResponse)

	if err != nil {
		return err
	}

	*o = WebhookKeyCreateResponse(varWebhookKeyCreateResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object")
		delete(additionalProperties, "active")
		delete(additionalProperties, "livemode")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "deactivated_at")
		delete(additionalProperties, "deleted")
		delete(additionalProperties, "public_key")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWebhookKeyCreateResponse struct {
	value *WebhookKeyCreateResponse
	isSet bool
}

func (v NullableWebhookKeyCreateResponse) Get() *WebhookKeyCreateResponse {
	return v.value
}

func (v *NullableWebhookKeyCreateResponse) Set(val *WebhookKeyCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookKeyCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookKeyCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookKeyCreateResponse(val *WebhookKeyCreateResponse) *NullableWebhookKeyCreateResponse {
	return &NullableWebhookKeyCreateResponse{value: val, isSet: true}
}

func (v NullableWebhookKeyCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookKeyCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


